# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rewind/v1/api.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rewind/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rewind.v1 import health_pb2 as rewind_dot_v1_dot_health__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13rewind/v1/api.proto\x12\trewind.v1\x1a\x16rewind/v1/health.proto\"&\n\x16GetSystemHealthRequest\x12\x0c\n\x04\x64\x65\x65p\x18\x01 \x01(\x08\"\x93\x01\n\x17GetSystemHealthResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.rewind.v1.HealthStatus\x12\'\n\x03\x61pi\x18\x02 \x01(\x0b\x32\x1a.rewind.v1.ComponentHealth\x12&\n\x02\x61i\x18\x03 \x01(\x0b\x32\x1a.rewind.v1.ComponentHealth\"\xaa\x01\n\x0f\x43omponentHealth\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.rewind.v1.HealthStatus\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x03\x12+\n\x0c\x64\x65pendencies\x18\x06 \x03(\x0b\x32\x15.rewind.v1.Dependency2i\n\rRewindService\x12X\n\x0fGetSystemHealth\x12!.rewind.v1.GetSystemHealthRequest\x1a\".rewind.v1.GetSystemHealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rewind.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSYSTEMHEALTHREQUEST']._serialized_start=58
  _globals['_GETSYSTEMHEALTHREQUEST']._serialized_end=96
  _globals['_GETSYSTEMHEALTHRESPONSE']._serialized_start=99
  _globals['_GETSYSTEMHEALTHRESPONSE']._serialized_end=246
  _globals['_COMPONENTHEALTH']._serialized_start=249
  _globals['_COMPONENTHEALTH']._serialized_end=419
  _globals['_REWINDSERVICE']._serialized_start=421
  _globals['_REWINDSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
