"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import api_pb2 as _api_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RewindServiceStub:
    """RewindService is the API the Next.js dashboard calls. Go serves it over the
    Connect protocol, which is plain JSON over HTTP -- browsers cannot speak
    native gRPC (SPEC.md 2.5).

    This service is the OUTER edge. The gRPC services in the other files are the
    INNER edge, between Go and the Python worker. They are deliberately separate:
    the dashboard's shape should be free to change without touching the worker
    contract, and vice versa.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RewindServiceAsyncStub: ...
    GetSystemHealth: _grpc.UnaryUnaryMultiCallable[_api_pb2.GetSystemHealthRequest, _api_pb2.GetSystemHealthResponse]
    """GetSystemHealth reports the health of every service in the system. In M0
    this is the only RPC, and it is what turns the dashboard chip green.
    """

@_typing.type_check_only
class RewindServiceAsyncStub(RewindServiceStub):
    """RewindService is the API the Next.js dashboard calls. Go serves it over the
    Connect protocol, which is plain JSON over HTTP -- browsers cannot speak
    native gRPC (SPEC.md 2.5).

    This service is the OUTER edge. The gRPC services in the other files are the
    INNER edge, between Go and the Python worker. They are deliberately separate:
    the dashboard's shape should be free to change without touching the worker
    contract, and vice versa.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetSystemHealth: _aio.UnaryUnaryMultiCallable[_api_pb2.GetSystemHealthRequest, _api_pb2.GetSystemHealthResponse]  # type: ignore[assignment]
    """GetSystemHealth reports the health of every service in the system. In M0
    this is the only RPC, and it is what turns the dashboard chip green.
    """

class RewindServiceServicer(metaclass=_abc_1.ABCMeta):
    """RewindService is the API the Next.js dashboard calls. Go serves it over the
    Connect protocol, which is plain JSON over HTTP -- browsers cannot speak
    native gRPC (SPEC.md 2.5).

    This service is the OUTER edge. The gRPC services in the other files are the
    INNER edge, between Go and the Python worker. They are deliberately separate:
    the dashboard's shape should be free to change without touching the worker
    contract, and vice versa.
    """

    @_abc_1.abstractmethod
    def GetSystemHealth(
        self,
        request: _api_pb2.GetSystemHealthRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_api_pb2.GetSystemHealthResponse, _abc.Awaitable[_api_pb2.GetSystemHealthResponse]]:
        """GetSystemHealth reports the health of every service in the system. In M0
        this is the only RPC, and it is what turns the dashboard chip green.
        """

def add_RewindServiceServicer_to_server(servicer: RewindServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
