# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import api_pb2 as rewind_dot_v1_dot_api__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RewindServiceStub:
    """RewindService is the API the Next.js dashboard calls. Go serves it over the
    Connect protocol, which is plain JSON over HTTP -- browsers cannot speak
    native gRPC (SPEC.md 2.5).

    This service is the OUTER edge. The gRPC services in the other files are the
    INNER edge, between Go and the Python worker. They are deliberately separate:
    the dashboard's shape should be free to change without touching the worker
    contract, and vice versa.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemHealth = channel.unary_unary(
                '/rewind.v1.RewindService/GetSystemHealth',
                request_serializer=rewind_dot_v1_dot_api__pb2.GetSystemHealthRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_api__pb2.GetSystemHealthResponse.FromString,
                _registered_method=True)


class RewindServiceServicer:
    """RewindService is the API the Next.js dashboard calls. Go serves it over the
    Connect protocol, which is plain JSON over HTTP -- browsers cannot speak
    native gRPC (SPEC.md 2.5).

    This service is the OUTER edge. The gRPC services in the other files are the
    INNER edge, between Go and the Python worker. They are deliberately separate:
    the dashboard's shape should be free to change without touching the worker
    contract, and vice versa.
    """

    def GetSystemHealth(self, request, context):
        """GetSystemHealth reports the health of every service in the system. In M0
        this is the only RPC, and it is what turns the dashboard chip green.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RewindServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemHealth,
                    request_deserializer=rewind_dot_v1_dot_api__pb2.GetSystemHealthRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_api__pb2.GetSystemHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.RewindService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.RewindService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RewindService:
    """RewindService is the API the Next.js dashboard calls. Go serves it over the
    Connect protocol, which is plain JSON over HTTP -- browsers cannot speak
    native gRPC (SPEC.md 2.5).

    This service is the OUTER edge. The gRPC services in the other files are the
    INNER edge, between Go and the Python worker. They are deliberately separate:
    the dashboard's shape should be free to change without touching the worker
    contract, and vice versa.
    """

    @staticmethod
    def GetSystemHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.RewindService/GetSystemHealth',
            rewind_dot_v1_dot_api__pb2.GetSystemHealthRequest.SerializeToString,
            rewind_dot_v1_dot_api__pb2.GetSystemHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
