"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from rewind.v1 import health_pb2 as _health_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetSystemHealthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEEP_FIELD_NUMBER: _builtins.int
    deep: _builtins.bool
    """Forwarded to the AI worker; see CheckRequest.deep."""
    def __init__(
        self,
        *,
        deep: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deep", b"deep"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSystemHealthRequest: _TypeAlias = GetSystemHealthRequest  # noqa: Y015

@_typing.final
class GetSystemHealthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    API_FIELD_NUMBER: _builtins.int
    AI_FIELD_NUMBER: _builtins.int
    status: _health_pb2.HealthStatus.ValueType
    """Worst status across every component."""
    @_builtins.property
    def api(self) -> Global___ComponentHealth:
        """The Go API itself. Always reachable if this response arrived at all, but
        carries the build version.
        """

    @_builtins.property
    def ai(self) -> Global___ComponentHealth:
        """The Python AI worker, reached over gRPC. This is the interesting one: it
        is DOWN when the worker is stopped, and the dashboard must degrade
        gracefully rather than error.
        """

    def __init__(
        self,
        *,
        status: _health_pb2.HealthStatus.ValueType = ...,
        api: Global___ComponentHealth | None = ...,
        ai: Global___ComponentHealth | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ai", b"ai", "api", b"api"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ai", b"ai", "api", b"api", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSystemHealthResponse: _TypeAlias = GetSystemHealthResponse  # noqa: Y015

@_typing.final
class ComponentHealth(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    LATENCY_MS_FIELD_NUMBER: _builtins.int
    DEPENDENCIES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    status: _health_pb2.HealthStatus.ValueType
    version: _builtins.str
    detail: _builtins.str
    """Populated on failure, e.g. "dial tcp 127.0.0.1:50051: connection refused"."""
    latency_ms: _builtins.int
    """Round-trip time of the check, in milliseconds."""
    @_builtins.property
    def dependencies(self) -> _containers.RepeatedCompositeFieldContainer[_health_pb2.Dependency]:
        """Per-dependency detail, only when deep was requested."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        status: _health_pb2.HealthStatus.ValueType = ...,
        version: _builtins.str = ...,
        detail: _builtins.str = ...,
        latency_ms: _builtins.int = ...,
        dependencies: _abc.Iterable[_health_pb2.Dependency] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dependencies", b"dependencies", "detail", b"detail", "latency_ms", b"latency_ms", "name", b"name", "status", b"status", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ComponentHealth: _TypeAlias = ComponentHealth  # noqa: Y015
