"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Package rewind.v1 is the contract between the Go API (api/) and the Python
AI worker (ai/). It is also generated for TypeScript so the Next.js
dashboard (web/) never hand-writes an API type.

Rules (SPEC.md 2.5):
  - Messages carry PATHS, not bytes. Media never travels over gRPC.
  - Every long-running RPC is server-streaming and emits Progress events.
  - Field numbers are the wire format: never reuse or renumber a shipped field.
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import typing as _typing

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
