"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Package rewind.v1 is the contract between the Go API (api/) and the Python
AI worker (ai/). It is also generated for TypeScript so the Next.js
dashboard (web/) never hand-writes an API type.

Rules (SPEC.md 2.5):
  - Messages carry PATHS, not bytes. Media never travels over gRPC.
  - Every long-running RPC is server-streaming and emits Progress events.
  - Field numbers are the wire format: never reuse or renumber a shipped field.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Progress(_message.Message):
    """Progress is emitted repeatedly while a long job runs, so the dashboard can
    show a real progress bar instead of an indefinite spinner.
    """

    DESCRIPTOR: _descriptor.Descriptor

    STAGE_FIELD_NUMBER: _builtins.int
    PERCENT_FIELD_NUMBER: _builtins.int
    CURRENT_FIELD_NUMBER: _builtins.int
    TOTAL_FIELD_NUMBER: _builtins.int
    stage: _builtins.str
    """Human-readable stage, shown verbatim in the UI. e.g. "fetching wikipedia"."""
    percent: _builtins.float
    """0.0 to 1.0. Best effort; the UI falls back to indeterminate when unset."""
    current: _builtins.int
    """Optional sub-step counters, e.g. beat 7 of 12."""
    total: _builtins.int
    def __init__(
        self,
        *,
        stage: _builtins.str = ...,
        percent: _builtins.float = ...,
        current: _builtins.int = ...,
        total: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current", b"current", "percent", b"percent", "stage", b"stage", "total", b"total"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Progress: _TypeAlias = Progress  # noqa: Y015

@_typing.final
class Failure(_message.Message):
    """Failure is the terminal event when a job cannot complete.

    Python reports WHAT went wrong. Go decides what that MEANS for the video's
    status -- the AI worker never sets a status itself.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    RETRYABLE_FIELD_NUMBER: _builtins.int
    code: _builtins.str
    """Stable machine-readable code, e.g. "SOURCE_UNREACHABLE", "MODEL_MISSING"."""
    message: _builtins.str
    """Operator-facing detail, safe to show in the dashboard."""
    retryable: _builtins.bool
    """Whether Go should retry with backoff. Transient infrastructure problems
    set this true; deterministic problems (validation) set it false.
    """
    def __init__(
        self,
        *,
        code: _builtins.str = ...,
        message: _builtins.str = ...,
        retryable: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message", "retryable", b"retryable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Failure: _TypeAlias = Failure  # noqa: Y015

@_typing.final
class VideoRef(_message.Message):
    """VideoRef identifies the project folder a job reads from and writes to.
    The id is validated against ^[a-z0-9-]{1,64}$ at the Go boundary before it
    is ever used to build a path (SPEC.md 13.5).
    """

    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VideoRef: _TypeAlias = VideoRef  # noqa: Y015
