"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from rewind.v1 import research_pb2 as _research_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FactsView(_message.Message):
    """FactsView is the whole reviewable state of Gate A."""

    DESCRIPTOR: _descriptor.Descriptor

    EXISTS_FIELD_NUMBER: _builtins.int
    SHEET_FIELD_NUMBER: _builtins.int
    CAN_APPROVE_FIELD_NUMBER: _builtins.int
    APPROVAL_BLOCKER_FIELD_NUMBER: _builtins.int
    APPROVED_COUNT_FIELD_NUMBER: _builtins.int
    ERA_COUNT_FIELD_NUMBER: _builtins.int
    exists: _builtins.bool
    """False until the research step has run."""
    can_approve: _builtins.bool
    """Whether Gate A can be approved yet, and why not."""
    approval_blocker: _builtins.str
    """e.g. "6 of 8 facts approved" or "facts span only 3 eras, need 4"."""
    approved_count: _builtins.int
    era_count: _builtins.int
    @_builtins.property
    def sheet(self) -> _research_pb2.FactSheet: ...
    def __init__(
        self,
        *,
        exists: _builtins.bool = ...,
        sheet: _research_pb2.FactSheet | None = ...,
        can_approve: _builtins.bool = ...,
        approval_blocker: _builtins.str = ...,
        approved_count: _builtins.int = ...,
        era_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sheet", b"sheet"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approval_blocker", b"approval_blocker", "approved_count", b"approved_count", "can_approve", b"can_approve", "era_count", b"era_count", "exists", b"exists", "sheet", b"sheet"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FactsView: _TypeAlias = FactsView  # noqa: Y015

@_typing.final
class GetFactsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetFactsRequest: _TypeAlias = GetFactsRequest  # noqa: Y015

@_typing.final
class GetFactsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___FactsView: ...
    def __init__(
        self,
        *,
        view: Global___FactsView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetFactsResponse: _TypeAlias = GetFactsResponse  # noqa: Y015

@_typing.final
class SetFactApprovalRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    FACT_ID_FIELD_NUMBER: _builtins.int
    APPROVED_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    fact_id: _builtins.str
    approved: _builtins.bool
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        fact_id: _builtins.str = ...,
        approved: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approved", b"approved", "fact_id", b"fact_id", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetFactApprovalRequest: _TypeAlias = SetFactApprovalRequest  # noqa: Y015

@_typing.final
class SetFactApprovalResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___FactsView: ...
    def __init__(
        self,
        *,
        view: Global___FactsView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetFactApprovalResponse: _TypeAlias = SetFactApprovalResponse  # noqa: Y015

@_typing.final
class ApproveAllFactsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    APPROVED_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    approved: _builtins.bool
    """false unticks everything"""
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        approved: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approved", b"approved", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApproveAllFactsRequest: _TypeAlias = ApproveAllFactsRequest  # noqa: Y015

@_typing.final
class ApproveAllFactsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___FactsView: ...
    def __init__(
        self,
        *,
        view: Global___FactsView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApproveAllFactsResponse: _TypeAlias = ApproveAllFactsResponse  # noqa: Y015

@_typing.final
class UpdateFactRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    FACT_ID_FIELD_NUMBER: _builtins.int
    YEAR_LABEL_FIELD_NUMBER: _builtins.int
    SORT_YEAR_FIELD_NUMBER: _builtins.int
    PLACE_FIELD_NUMBER: _builtins.int
    CLAIM_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    fact_id: _builtins.str
    year_label: _builtins.str
    """Only these fields are editable; evidence and source_url are not."""
    sort_year: _builtins.int
    place: _builtins.str
    claim: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        fact_id: _builtins.str = ...,
        year_label: _builtins.str = ...,
        sort_year: _builtins.int = ...,
        place: _builtins.str = ...,
        claim: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim", "fact_id", b"fact_id", "place", b"place", "sort_year", b"sort_year", "video_id", b"video_id", "year_label", b"year_label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateFactRequest: _TypeAlias = UpdateFactRequest  # noqa: Y015

@_typing.final
class UpdateFactResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___FactsView: ...
    def __init__(
        self,
        *,
        view: Global___FactsView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateFactResponse: _TypeAlias = UpdateFactResponse  # noqa: Y015

@_typing.final
class DeleteFactRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    FACT_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    fact_id: _builtins.str
    reason: _builtins.str
    """Recorded in the review log. Why you dropped a fact is worth keeping."""
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        fact_id: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fact_id", b"fact_id", "reason", b"reason", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteFactRequest: _TypeAlias = DeleteFactRequest  # noqa: Y015

@_typing.final
class DeleteFactResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___FactsView: ...
    def __init__(
        self,
        *,
        view: Global___FactsView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteFactResponse: _TypeAlias = DeleteFactResponse  # noqa: Y015

@_typing.final
class AddFactRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    YEAR_LABEL_FIELD_NUMBER: _builtins.int
    SORT_YEAR_FIELD_NUMBER: _builtins.int
    PLACE_FIELD_NUMBER: _builtins.int
    CLAIM_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    year_label: _builtins.str
    sort_year: _builtins.int
    place: _builtins.str
    claim: _builtins.str
    source_url: _builtins.str
    """Required. A human-added fact still needs somewhere it came from."""
    evidence: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        year_label: _builtins.str = ...,
        sort_year: _builtins.int = ...,
        place: _builtins.str = ...,
        claim: _builtins.str = ...,
        source_url: _builtins.str = ...,
        evidence: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim", "evidence", b"evidence", "place", b"place", "sort_year", b"sort_year", "source_url", b"source_url", "video_id", b"video_id", "year_label", b"year_label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddFactRequest: _TypeAlias = AddFactRequest  # noqa: Y015

@_typing.final
class AddFactResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___FactsView: ...
    def __init__(
        self,
        *,
        view: Global___FactsView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddFactResponse: _TypeAlias = AddFactResponse  # noqa: Y015
