"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import facts_pb2 as _facts_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class FactsServiceStub:
    """FactsService is the Gate A surface for the dashboard (SPEC.md 5.2, 8.2).

    Facts live in projects/<video_id>/facts.json, written by the Python worker.
    Every edit a human makes here is written back by Go, which owns all state.

    Every mutation returns the WHOLE updated view rather than just an
    acknowledgement. Gate A's approval rules depend on the sheet as a whole --
    how many facts are ticked, how many eras they span -- so returning the
    recomputed view means the dashboard can never show a stale verdict.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> FactsServiceAsyncStub: ...
    GetFacts: _grpc.UnaryUnaryMultiCallable[_facts_pb2.GetFactsRequest, _facts_pb2.GetFactsResponse]
    """GetFacts returns the fact sheet for review."""
    SetFactApproval: _grpc.UnaryUnaryMultiCallable[_facts_pb2.SetFactApprovalRequest, _facts_pb2.SetFactApprovalResponse]
    """SetFactApproval ticks or unticks one fact."""
    ApproveAllFacts: _grpc.UnaryUnaryMultiCallable[_facts_pb2.ApproveAllFactsRequest, _facts_pb2.ApproveAllFactsResponse]
    """ApproveAllFacts ticks every fact at once -- the common case when the
    research came back clean.
    """
    UpdateFact: _grpc.UnaryUnaryMultiCallable[_facts_pb2.UpdateFactRequest, _facts_pb2.UpdateFactResponse]
    """UpdateFact edits a fact's wording.

    The evidence and source_url of an extracted fact CANNOT be edited: they
    are the record of where the claim came from, and letting them be rewritten
    would defeat the verifier. Correcting a claim means editing the claim, or
    deleting the fact and adding your own.
    """
    DeleteFact: _grpc.UnaryUnaryMultiCallable[_facts_pb2.DeleteFactRequest, _facts_pb2.DeleteFactResponse]
    """DeleteFact removes a fact from the sheet."""
    AddFact: _grpc.UnaryUnaryMultiCallable[_facts_pb2.AddFactRequest, _facts_pb2.AddFactResponse]
    """AddFact adds a fact the human sourced themselves.

    Human-added facts skip the evidence verifier -- a person citing a book is
    the authority the verifier exists to substitute for -- but a source is
    still required, because SPEC.md 5.2 allows no unsourced claim.
    """

@_typing.type_check_only
class FactsServiceAsyncStub(FactsServiceStub):
    """FactsService is the Gate A surface for the dashboard (SPEC.md 5.2, 8.2).

    Facts live in projects/<video_id>/facts.json, written by the Python worker.
    Every edit a human makes here is written back by Go, which owns all state.

    Every mutation returns the WHOLE updated view rather than just an
    acknowledgement. Gate A's approval rules depend on the sheet as a whole --
    how many facts are ticked, how many eras they span -- so returning the
    recomputed view means the dashboard can never show a stale verdict.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetFacts: _aio.UnaryUnaryMultiCallable[_facts_pb2.GetFactsRequest, _facts_pb2.GetFactsResponse]  # type: ignore[assignment]
    """GetFacts returns the fact sheet for review."""
    SetFactApproval: _aio.UnaryUnaryMultiCallable[_facts_pb2.SetFactApprovalRequest, _facts_pb2.SetFactApprovalResponse]  # type: ignore[assignment]
    """SetFactApproval ticks or unticks one fact."""
    ApproveAllFacts: _aio.UnaryUnaryMultiCallable[_facts_pb2.ApproveAllFactsRequest, _facts_pb2.ApproveAllFactsResponse]  # type: ignore[assignment]
    """ApproveAllFacts ticks every fact at once -- the common case when the
    research came back clean.
    """
    UpdateFact: _aio.UnaryUnaryMultiCallable[_facts_pb2.UpdateFactRequest, _facts_pb2.UpdateFactResponse]  # type: ignore[assignment]
    """UpdateFact edits a fact's wording.

    The evidence and source_url of an extracted fact CANNOT be edited: they
    are the record of where the claim came from, and letting them be rewritten
    would defeat the verifier. Correcting a claim means editing the claim, or
    deleting the fact and adding your own.
    """
    DeleteFact: _aio.UnaryUnaryMultiCallable[_facts_pb2.DeleteFactRequest, _facts_pb2.DeleteFactResponse]  # type: ignore[assignment]
    """DeleteFact removes a fact from the sheet."""
    AddFact: _aio.UnaryUnaryMultiCallable[_facts_pb2.AddFactRequest, _facts_pb2.AddFactResponse]  # type: ignore[assignment]
    """AddFact adds a fact the human sourced themselves.

    Human-added facts skip the evidence verifier -- a person citing a book is
    the authority the verifier exists to substitute for -- but a source is
    still required, because SPEC.md 5.2 allows no unsourced claim.
    """

class FactsServiceServicer(metaclass=_abc_1.ABCMeta):
    """FactsService is the Gate A surface for the dashboard (SPEC.md 5.2, 8.2).

    Facts live in projects/<video_id>/facts.json, written by the Python worker.
    Every edit a human makes here is written back by Go, which owns all state.

    Every mutation returns the WHOLE updated view rather than just an
    acknowledgement. Gate A's approval rules depend on the sheet as a whole --
    how many facts are ticked, how many eras they span -- so returning the
    recomputed view means the dashboard can never show a stale verdict.
    """

    @_abc_1.abstractmethod
    def GetFacts(
        self,
        request: _facts_pb2.GetFactsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_facts_pb2.GetFactsResponse, _abc.Awaitable[_facts_pb2.GetFactsResponse]]:
        """GetFacts returns the fact sheet for review."""

    @_abc_1.abstractmethod
    def SetFactApproval(
        self,
        request: _facts_pb2.SetFactApprovalRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_facts_pb2.SetFactApprovalResponse, _abc.Awaitable[_facts_pb2.SetFactApprovalResponse]]:
        """SetFactApproval ticks or unticks one fact."""

    @_abc_1.abstractmethod
    def ApproveAllFacts(
        self,
        request: _facts_pb2.ApproveAllFactsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_facts_pb2.ApproveAllFactsResponse, _abc.Awaitable[_facts_pb2.ApproveAllFactsResponse]]:
        """ApproveAllFacts ticks every fact at once -- the common case when the
        research came back clean.
        """

    @_abc_1.abstractmethod
    def UpdateFact(
        self,
        request: _facts_pb2.UpdateFactRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_facts_pb2.UpdateFactResponse, _abc.Awaitable[_facts_pb2.UpdateFactResponse]]:
        """UpdateFact edits a fact's wording.

        The evidence and source_url of an extracted fact CANNOT be edited: they
        are the record of where the claim came from, and letting them be rewritten
        would defeat the verifier. Correcting a claim means editing the claim, or
        deleting the fact and adding your own.
        """

    @_abc_1.abstractmethod
    def DeleteFact(
        self,
        request: _facts_pb2.DeleteFactRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_facts_pb2.DeleteFactResponse, _abc.Awaitable[_facts_pb2.DeleteFactResponse]]:
        """DeleteFact removes a fact from the sheet."""

    @_abc_1.abstractmethod
    def AddFact(
        self,
        request: _facts_pb2.AddFactRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_facts_pb2.AddFactResponse, _abc.Awaitable[_facts_pb2.AddFactResponse]]:
        """AddFact adds a fact the human sourced themselves.

        Human-added facts skip the evidence verifier -- a person citing a book is
        the authority the verifier exists to substitute for -- but a source is
        still required, because SPEC.md 5.2 allows no unsourced claim.
        """

def add_FactsServiceServicer_to_server(servicer: FactsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
