# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import facts_pb2 as rewind_dot_v1_dot_facts__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/facts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FactsServiceStub:
    """FactsService is the Gate A surface for the dashboard (SPEC.md 5.2, 8.2).

    Facts live in projects/<video_id>/facts.json, written by the Python worker.
    Every edit a human makes here is written back by Go, which owns all state.

    Every mutation returns the WHOLE updated view rather than just an
    acknowledgement. Gate A's approval rules depend on the sheet as a whole --
    how many facts are ticked, how many eras they span -- so returning the
    recomputed view means the dashboard can never show a stale verdict.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFacts = channel.unary_unary(
                '/rewind.v1.FactsService/GetFacts',
                request_serializer=rewind_dot_v1_dot_facts__pb2.GetFactsRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_facts__pb2.GetFactsResponse.FromString,
                _registered_method=True)
        self.SetFactApproval = channel.unary_unary(
                '/rewind.v1.FactsService/SetFactApproval',
                request_serializer=rewind_dot_v1_dot_facts__pb2.SetFactApprovalRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_facts__pb2.SetFactApprovalResponse.FromString,
                _registered_method=True)
        self.ApproveAllFacts = channel.unary_unary(
                '/rewind.v1.FactsService/ApproveAllFacts',
                request_serializer=rewind_dot_v1_dot_facts__pb2.ApproveAllFactsRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_facts__pb2.ApproveAllFactsResponse.FromString,
                _registered_method=True)
        self.UpdateFact = channel.unary_unary(
                '/rewind.v1.FactsService/UpdateFact',
                request_serializer=rewind_dot_v1_dot_facts__pb2.UpdateFactRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_facts__pb2.UpdateFactResponse.FromString,
                _registered_method=True)
        self.DeleteFact = channel.unary_unary(
                '/rewind.v1.FactsService/DeleteFact',
                request_serializer=rewind_dot_v1_dot_facts__pb2.DeleteFactRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_facts__pb2.DeleteFactResponse.FromString,
                _registered_method=True)
        self.AddFact = channel.unary_unary(
                '/rewind.v1.FactsService/AddFact',
                request_serializer=rewind_dot_v1_dot_facts__pb2.AddFactRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_facts__pb2.AddFactResponse.FromString,
                _registered_method=True)


class FactsServiceServicer:
    """FactsService is the Gate A surface for the dashboard (SPEC.md 5.2, 8.2).

    Facts live in projects/<video_id>/facts.json, written by the Python worker.
    Every edit a human makes here is written back by Go, which owns all state.

    Every mutation returns the WHOLE updated view rather than just an
    acknowledgement. Gate A's approval rules depend on the sheet as a whole --
    how many facts are ticked, how many eras they span -- so returning the
    recomputed view means the dashboard can never show a stale verdict.
    """

    def GetFacts(self, request, context):
        """GetFacts returns the fact sheet for review.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFactApproval(self, request, context):
        """SetFactApproval ticks or unticks one fact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAllFacts(self, request, context):
        """ApproveAllFacts ticks every fact at once -- the common case when the
        research came back clean.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFact(self, request, context):
        """UpdateFact edits a fact's wording.

        The evidence and source_url of an extracted fact CANNOT be edited: they
        are the record of where the claim came from, and letting them be rewritten
        would defeat the verifier. Correcting a claim means editing the claim, or
        deleting the fact and adding your own.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFact(self, request, context):
        """DeleteFact removes a fact from the sheet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFact(self, request, context):
        """AddFact adds a fact the human sourced themselves.

        Human-added facts skip the evidence verifier -- a person citing a book is
        the authority the verifier exists to substitute for -- but a source is
        still required, because SPEC.md 5.2 allows no unsourced claim.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFacts,
                    request_deserializer=rewind_dot_v1_dot_facts__pb2.GetFactsRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_facts__pb2.GetFactsResponse.SerializeToString,
            ),
            'SetFactApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFactApproval,
                    request_deserializer=rewind_dot_v1_dot_facts__pb2.SetFactApprovalRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_facts__pb2.SetFactApprovalResponse.SerializeToString,
            ),
            'ApproveAllFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAllFacts,
                    request_deserializer=rewind_dot_v1_dot_facts__pb2.ApproveAllFactsRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_facts__pb2.ApproveAllFactsResponse.SerializeToString,
            ),
            'UpdateFact': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFact,
                    request_deserializer=rewind_dot_v1_dot_facts__pb2.UpdateFactRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_facts__pb2.UpdateFactResponse.SerializeToString,
            ),
            'DeleteFact': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFact,
                    request_deserializer=rewind_dot_v1_dot_facts__pb2.DeleteFactRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_facts__pb2.DeleteFactResponse.SerializeToString,
            ),
            'AddFact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFact,
                    request_deserializer=rewind_dot_v1_dot_facts__pb2.AddFactRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_facts__pb2.AddFactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.FactsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.FactsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FactsService:
    """FactsService is the Gate A surface for the dashboard (SPEC.md 5.2, 8.2).

    Facts live in projects/<video_id>/facts.json, written by the Python worker.
    Every edit a human makes here is written back by Go, which owns all state.

    Every mutation returns the WHOLE updated view rather than just an
    acknowledgement. Gate A's approval rules depend on the sheet as a whole --
    how many facts are ticked, how many eras they span -- so returning the
    recomputed view means the dashboard can never show a stale verdict.
    """

    @staticmethod
    def GetFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.FactsService/GetFacts',
            rewind_dot_v1_dot_facts__pb2.GetFactsRequest.SerializeToString,
            rewind_dot_v1_dot_facts__pb2.GetFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFactApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.FactsService/SetFactApproval',
            rewind_dot_v1_dot_facts__pb2.SetFactApprovalRequest.SerializeToString,
            rewind_dot_v1_dot_facts__pb2.SetFactApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAllFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.FactsService/ApproveAllFacts',
            rewind_dot_v1_dot_facts__pb2.ApproveAllFactsRequest.SerializeToString,
            rewind_dot_v1_dot_facts__pb2.ApproveAllFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.FactsService/UpdateFact',
            rewind_dot_v1_dot_facts__pb2.UpdateFactRequest.SerializeToString,
            rewind_dot_v1_dot_facts__pb2.UpdateFactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.FactsService/DeleteFact',
            rewind_dot_v1_dot_facts__pb2.DeleteFactRequest.SerializeToString,
            rewind_dot_v1_dot_facts__pb2.DeleteFactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.FactsService/AddFact',
            rewind_dot_v1_dot_facts__pb2.AddFactRequest.SerializeToString,
            rewind_dot_v1_dot_facts__pb2.AddFactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
