# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rewind/v1/health.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rewind/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16rewind/v1/health.proto\x12\trewind.v1\"\x1c\n\x0c\x43heckRequest\x12\x0c\n\x04\x64\x65\x65p\x18\x01 \x01(\x08\"S\n\nDependency\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.rewind.v1.HealthStatus\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"v\n\rCheckResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.rewind.v1.HealthStatus\x12\x0f\n\x07version\x18\x02 \x01(\t\x12+\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32\x15.rewind.v1.Dependency*w\n\x0cHealthStatus\x12\x1d\n\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x14\n\x10HEALTH_STATUS_OK\x10\x01\x12\x1a\n\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x16\n\x12HEALTH_STATUS_DOWN\x10\x03\x32K\n\rHealthService\x12:\n\x05\x43heck\x12\x17.rewind.v1.CheckRequest\x1a\x18.rewind.v1.CheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rewind.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHSTATUS']._serialized_start=272
  _globals['_HEALTHSTATUS']._serialized_end=391
  _globals['_CHECKREQUEST']._serialized_start=37
  _globals['_CHECKREQUEST']._serialized_end=65
  _globals['_DEPENDENCY']._serialized_start=67
  _globals['_DEPENDENCY']._serialized_end=150
  _globals['_CHECKRESPONSE']._serialized_start=152
  _globals['_CHECKRESPONSE']._serialized_end=270
  _globals['_HEALTHSERVICE']._serialized_start=393
  _globals['_HEALTHSERVICE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
