"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _HealthStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HealthStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_HealthStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HEALTH_STATUS_UNSPECIFIED: _HealthStatus.ValueType  # 0
    HEALTH_STATUS_OK: _HealthStatus.ValueType  # 1
    """Everything needed is present and working."""
    HEALTH_STATUS_DEGRADED: _HealthStatus.ValueType  # 2
    """Usable, but something is missing that will matter in a later milestone."""
    HEALTH_STATUS_DOWN: _HealthStatus.ValueType  # 3
    """Cannot do useful work."""

class HealthStatus(_HealthStatus, metaclass=_HealthStatusEnumTypeWrapper):
    """Status of one dependency, or of the worker overall."""

HEALTH_STATUS_UNSPECIFIED: HealthStatus.ValueType  # 0
HEALTH_STATUS_OK: HealthStatus.ValueType  # 1
"""Everything needed is present and working."""
HEALTH_STATUS_DEGRADED: HealthStatus.ValueType  # 2
"""Usable, but something is missing that will matter in a later milestone."""
HEALTH_STATUS_DOWN: HealthStatus.ValueType  # 3
"""Cannot do useful work."""
Global___HealthStatus: _TypeAlias = HealthStatus  # noqa: Y015

@_typing.final
class CheckRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEEP_FIELD_NUMBER: _builtins.int
    deep: _builtins.bool
    """When true, the worker probes its heavy dependencies (Ollama reachable,
    model pulled, GPU visible, ffmpeg on PATH) instead of only reporting that
    the process is alive. `rewind doctor` sets this; a dashboard poll does not.
    """
    def __init__(
        self,
        *,
        deep: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deep", b"deep"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckRequest: _TypeAlias = CheckRequest  # noqa: Y015

@_typing.final
class Dependency(_message.Message):
    """One probed dependency, e.g. "ollama", "gpu", "ffmpeg"."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    DETAIL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    status: Global___HealthStatus.ValueType
    detail: _builtins.str
    """Short human-readable detail, e.g. "model qwen2.5:14b not pulled"."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        status: Global___HealthStatus.ValueType = ...,
        detail: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail", "name", b"name", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Dependency: _TypeAlias = Dependency  # noqa: Y015

@_typing.final
class CheckResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DEPENDENCIES_FIELD_NUMBER: _builtins.int
    status: Global___HealthStatus.ValueType
    """Worst status across all dependencies."""
    version: _builtins.str
    """Version of the AI worker, for the dashboard footer and bug reports."""
    @_builtins.property
    def dependencies(self) -> _containers.RepeatedCompositeFieldContainer[Global___Dependency]:
        """Only populated when the request set deep = true."""

    def __init__(
        self,
        *,
        status: Global___HealthStatus.ValueType = ...,
        version: _builtins.str = ...,
        dependencies: _abc.Iterable[Global___Dependency] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dependencies", b"dependencies", "status", b"status", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckResponse: _TypeAlias = CheckResponse  # noqa: Y015
