"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import health_pb2 as _health_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class HealthServiceStub:
    """HealthService is the only service M0 implements. It exists so the whole
    spine -- browser to Go to gRPC to Python -- can be proven end to end before
    any AI code is written, and so `rewind doctor` has something to call later.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> HealthServiceAsyncStub: ...
    Check: _grpc.UnaryUnaryMultiCallable[_health_pb2.CheckRequest, _health_pb2.CheckResponse]
    """Check reports whether the AI worker and its dependencies are usable."""

@_typing.type_check_only
class HealthServiceAsyncStub(HealthServiceStub):
    """HealthService is the only service M0 implements. It exists so the whole
    spine -- browser to Go to gRPC to Python -- can be proven end to end before
    any AI code is written, and so `rewind doctor` has something to call later.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Check: _aio.UnaryUnaryMultiCallable[_health_pb2.CheckRequest, _health_pb2.CheckResponse]  # type: ignore[assignment]
    """Check reports whether the AI worker and its dependencies are usable."""

class HealthServiceServicer(metaclass=_abc_1.ABCMeta):
    """HealthService is the only service M0 implements. It exists so the whole
    spine -- browser to Go to gRPC to Python -- can be proven end to end before
    any AI code is written, and so `rewind doctor` has something to call later.
    """

    @_abc_1.abstractmethod
    def Check(
        self,
        request: _health_pb2.CheckRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_health_pb2.CheckResponse, _abc.Awaitable[_health_pb2.CheckResponse]]:
        """Check reports whether the AI worker and its dependencies are usable."""

def add_HealthServiceServicer_to_server(servicer: HealthServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
