"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from rewind.v1 import relevance_pb2 as _relevance_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReferencesView(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXISTS_FIELD_NUMBER: _builtins.int
    SHEET_FIELD_NUMBER: _builtins.int
    CAN_APPROVE_FIELD_NUMBER: _builtins.int
    APPROVAL_BLOCKER_FIELD_NUMBER: _builtins.int
    SELECTED_COUNT_FIELD_NUMBER: _builtins.int
    MAX_SELECTABLE_FIELD_NUMBER: _builtins.int
    STALE_REFERENCE_IDS_FIELD_NUMBER: _builtins.int
    exists: _builtins.bool
    """False until the relevance step has run."""
    can_approve: _builtins.bool
    approval_blocker: _builtins.str
    """e.g. "nothing selected yet" or "4 selected, the limit is 3"."""
    selected_count: _builtins.int
    max_selectable: _builtins.int
    @_builtins.property
    def sheet(self) -> _relevance_pb2.ReferenceSheet: ...
    @_builtins.property
    def stale_reference_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Selected HOT references whose freshness date has passed. Not fatal at
        Gate B -- you may still want them -- but Gate F warns, so it is better to
        know now (SPEC.md 5.3).
        """

    def __init__(
        self,
        *,
        exists: _builtins.bool = ...,
        sheet: _relevance_pb2.ReferenceSheet | None = ...,
        can_approve: _builtins.bool = ...,
        approval_blocker: _builtins.str = ...,
        selected_count: _builtins.int = ...,
        max_selectable: _builtins.int = ...,
        stale_reference_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sheet", b"sheet"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approval_blocker", b"approval_blocker", "can_approve", b"can_approve", "exists", b"exists", "max_selectable", b"max_selectable", "selected_count", b"selected_count", "sheet", b"sheet", "stale_reference_ids", b"stale_reference_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReferencesView: _TypeAlias = ReferencesView  # noqa: Y015

@_typing.final
class GetReferencesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetReferencesRequest: _TypeAlias = GetReferencesRequest  # noqa: Y015

@_typing.final
class GetReferencesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ReferencesView: ...
    def __init__(
        self,
        *,
        view: Global___ReferencesView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetReferencesResponse: _TypeAlias = GetReferencesResponse  # noqa: Y015

@_typing.final
class SelectProposalRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    PROPOSAL_ID_FIELD_NUMBER: _builtins.int
    SELECTED_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    proposal_id: _builtins.str
    selected: _builtins.bool
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        proposal_id: _builtins.str = ...,
        selected: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proposal_id", b"proposal_id", "selected", b"selected", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SelectProposalRequest: _TypeAlias = SelectProposalRequest  # noqa: Y015

@_typing.final
class SelectProposalResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ReferencesView: ...
    def __init__(
        self,
        *,
        view: Global___ReferencesView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SelectProposalResponse: _TypeAlias = SelectProposalResponse  # noqa: Y015

@_typing.final
class UpdateProposalRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    PROPOSAL_ID_FIELD_NUMBER: _builtins.int
    COMPARISON_FIELD_NUMBER: _builtins.int
    WHY_FUNNY_FIELD_NUMBER: _builtins.int
    LINKED_FACT_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    proposal_id: _builtins.str
    comparison: _builtins.str
    why_funny: _builtins.str
    linked_fact_id: _builtins.str
    """Re-pointing a comparison at a different approved fact."""
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        proposal_id: _builtins.str = ...,
        comparison: _builtins.str = ...,
        why_funny: _builtins.str = ...,
        linked_fact_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comparison", b"comparison", "linked_fact_id", b"linked_fact_id", "proposal_id", b"proposal_id", "video_id", b"video_id", "why_funny", b"why_funny"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateProposalRequest: _TypeAlias = UpdateProposalRequest  # noqa: Y015

@_typing.final
class UpdateProposalResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ReferencesView: ...
    def __init__(
        self,
        *,
        view: Global___ReferencesView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateProposalResponse: _TypeAlias = UpdateProposalResponse  # noqa: Y015

@_typing.final
class DeleteProposalRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    PROPOSAL_ID_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    proposal_id: _builtins.str
    reason: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        proposal_id: _builtins.str = ...,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proposal_id", b"proposal_id", "reason", b"reason", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteProposalRequest: _TypeAlias = DeleteProposalRequest  # noqa: Y015

@_typing.final
class DeleteProposalResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ReferencesView: ...
    def __init__(
        self,
        *,
        view: Global___ReferencesView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteProposalResponse: _TypeAlias = DeleteProposalResponse  # noqa: Y015

@_typing.final
class AddProposalRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    COMPARISON_FIELD_NUMBER: _builtins.int
    WHY_FUNNY_FIELD_NUMBER: _builtins.int
    LINKED_FACT_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    reference: _builtins.str
    comparison: _builtins.str
    why_funny: _builtins.str
    linked_fact_id: _builtins.str
    """Required: a comparison must attach to an approved fact."""
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        reference: _builtins.str = ...,
        comparison: _builtins.str = ...,
        why_funny: _builtins.str = ...,
        linked_fact_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comparison", b"comparison", "linked_fact_id", b"linked_fact_id", "reference", b"reference", "video_id", b"video_id", "why_funny", b"why_funny"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddProposalRequest: _TypeAlias = AddProposalRequest  # noqa: Y015

@_typing.final
class AddProposalResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ReferencesView: ...
    def __init__(
        self,
        *,
        view: Global___ReferencesView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddProposalResponse: _TypeAlias = AddProposalResponse  # noqa: Y015
