"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import references_pb2 as _references_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ReferencesServiceStub:
    """ReferencesService is the Gate B surface for the dashboard (SPEC.md 5.3, 8.2).

    The shape mirrors FactsService deliberately: every mutation returns the whole
    recomputed view, because Gate B's rules depend on the sheet as a whole -- how
    many are selected, whether any has expired.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ReferencesServiceAsyncStub: ...
    GetReferences: _grpc.UnaryUnaryMultiCallable[_references_pb2.GetReferencesRequest, _references_pb2.GetReferencesResponse]
    SelectProposal: _grpc.UnaryUnaryMultiCallable[_references_pb2.SelectProposalRequest, _references_pb2.SelectProposalResponse]
    """SelectProposal ticks or unticks one comparison.

    Selecting more than max_selectable is refused rather than silently
    dropping one: three is a hard limit on how much of a video can be
    "basically a modern brand" before it stops being history (SPEC.md 5.3).
    """
    UpdateProposal: _grpc.UnaryUnaryMultiCallable[_references_pb2.UpdateProposalRequest, _references_pb2.UpdateProposalResponse]
    """UpdateProposal rewrites a comparison's wording."""
    DeleteProposal: _grpc.UnaryUnaryMultiCallable[_references_pb2.DeleteProposalRequest, _references_pb2.DeleteProposalResponse]
    """DeleteProposal removes one from the sheet."""
    AddProposal: _grpc.UnaryUnaryMultiCallable[_references_pb2.AddProposalRequest, _references_pb2.AddProposalResponse]
    """AddProposal adds a comparison the human wrote themselves, or a trend they
    pasted in from somewhere the scanner cannot reach (TikTok, Instagram).
    """

@_typing.type_check_only
class ReferencesServiceAsyncStub(ReferencesServiceStub):
    """ReferencesService is the Gate B surface for the dashboard (SPEC.md 5.3, 8.2).

    The shape mirrors FactsService deliberately: every mutation returns the whole
    recomputed view, because Gate B's rules depend on the sheet as a whole -- how
    many are selected, whether any has expired.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetReferences: _aio.UnaryUnaryMultiCallable[_references_pb2.GetReferencesRequest, _references_pb2.GetReferencesResponse]  # type: ignore[assignment]
    SelectProposal: _aio.UnaryUnaryMultiCallable[_references_pb2.SelectProposalRequest, _references_pb2.SelectProposalResponse]  # type: ignore[assignment]
    """SelectProposal ticks or unticks one comparison.

    Selecting more than max_selectable is refused rather than silently
    dropping one: three is a hard limit on how much of a video can be
    "basically a modern brand" before it stops being history (SPEC.md 5.3).
    """
    UpdateProposal: _aio.UnaryUnaryMultiCallable[_references_pb2.UpdateProposalRequest, _references_pb2.UpdateProposalResponse]  # type: ignore[assignment]
    """UpdateProposal rewrites a comparison's wording."""
    DeleteProposal: _aio.UnaryUnaryMultiCallable[_references_pb2.DeleteProposalRequest, _references_pb2.DeleteProposalResponse]  # type: ignore[assignment]
    """DeleteProposal removes one from the sheet."""
    AddProposal: _aio.UnaryUnaryMultiCallable[_references_pb2.AddProposalRequest, _references_pb2.AddProposalResponse]  # type: ignore[assignment]
    """AddProposal adds a comparison the human wrote themselves, or a trend they
    pasted in from somewhere the scanner cannot reach (TikTok, Instagram).
    """

class ReferencesServiceServicer(metaclass=_abc_1.ABCMeta):
    """ReferencesService is the Gate B surface for the dashboard (SPEC.md 5.3, 8.2).

    The shape mirrors FactsService deliberately: every mutation returns the whole
    recomputed view, because Gate B's rules depend on the sheet as a whole -- how
    many are selected, whether any has expired.
    """

    @_abc_1.abstractmethod
    def GetReferences(
        self,
        request: _references_pb2.GetReferencesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_references_pb2.GetReferencesResponse, _abc.Awaitable[_references_pb2.GetReferencesResponse]]: ...

    @_abc_1.abstractmethod
    def SelectProposal(
        self,
        request: _references_pb2.SelectProposalRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_references_pb2.SelectProposalResponse, _abc.Awaitable[_references_pb2.SelectProposalResponse]]:
        """SelectProposal ticks or unticks one comparison.

        Selecting more than max_selectable is refused rather than silently
        dropping one: three is a hard limit on how much of a video can be
        "basically a modern brand" before it stops being history (SPEC.md 5.3).
        """

    @_abc_1.abstractmethod
    def UpdateProposal(
        self,
        request: _references_pb2.UpdateProposalRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_references_pb2.UpdateProposalResponse, _abc.Awaitable[_references_pb2.UpdateProposalResponse]]:
        """UpdateProposal rewrites a comparison's wording."""

    @_abc_1.abstractmethod
    def DeleteProposal(
        self,
        request: _references_pb2.DeleteProposalRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_references_pb2.DeleteProposalResponse, _abc.Awaitable[_references_pb2.DeleteProposalResponse]]:
        """DeleteProposal removes one from the sheet."""

    @_abc_1.abstractmethod
    def AddProposal(
        self,
        request: _references_pb2.AddProposalRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_references_pb2.AddProposalResponse, _abc.Awaitable[_references_pb2.AddProposalResponse]]:
        """AddProposal adds a comparison the human wrote themselves, or a trend they
        pasted in from somewhere the scanner cannot reach (TikTok, Instagram).
        """

def add_ReferencesServiceServicer_to_server(servicer: ReferencesServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
