# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import references_pb2 as rewind_dot_v1_dot_references__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/references_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReferencesServiceStub:
    """ReferencesService is the Gate B surface for the dashboard (SPEC.md 5.3, 8.2).

    The shape mirrors FactsService deliberately: every mutation returns the whole
    recomputed view, because Gate B's rules depend on the sheet as a whole -- how
    many are selected, whether any has expired.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReferences = channel.unary_unary(
                '/rewind.v1.ReferencesService/GetReferences',
                request_serializer=rewind_dot_v1_dot_references__pb2.GetReferencesRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_references__pb2.GetReferencesResponse.FromString,
                _registered_method=True)
        self.SelectProposal = channel.unary_unary(
                '/rewind.v1.ReferencesService/SelectProposal',
                request_serializer=rewind_dot_v1_dot_references__pb2.SelectProposalRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_references__pb2.SelectProposalResponse.FromString,
                _registered_method=True)
        self.UpdateProposal = channel.unary_unary(
                '/rewind.v1.ReferencesService/UpdateProposal',
                request_serializer=rewind_dot_v1_dot_references__pb2.UpdateProposalRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_references__pb2.UpdateProposalResponse.FromString,
                _registered_method=True)
        self.DeleteProposal = channel.unary_unary(
                '/rewind.v1.ReferencesService/DeleteProposal',
                request_serializer=rewind_dot_v1_dot_references__pb2.DeleteProposalRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_references__pb2.DeleteProposalResponse.FromString,
                _registered_method=True)
        self.AddProposal = channel.unary_unary(
                '/rewind.v1.ReferencesService/AddProposal',
                request_serializer=rewind_dot_v1_dot_references__pb2.AddProposalRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_references__pb2.AddProposalResponse.FromString,
                _registered_method=True)


class ReferencesServiceServicer:
    """ReferencesService is the Gate B surface for the dashboard (SPEC.md 5.3, 8.2).

    The shape mirrors FactsService deliberately: every mutation returns the whole
    recomputed view, because Gate B's rules depend on the sheet as a whole -- how
    many are selected, whether any has expired.
    """

    def GetReferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectProposal(self, request, context):
        """SelectProposal ticks or unticks one comparison.

        Selecting more than max_selectable is refused rather than silently
        dropping one: three is a hard limit on how much of a video can be
        "basically a modern brand" before it stops being history (SPEC.md 5.3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProposal(self, request, context):
        """UpdateProposal rewrites a comparison's wording.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProposal(self, request, context):
        """DeleteProposal removes one from the sheet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProposal(self, request, context):
        """AddProposal adds a comparison the human wrote themselves, or a trend they
        pasted in from somewhere the scanner cannot reach (TikTok, Instagram).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReferencesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReferences,
                    request_deserializer=rewind_dot_v1_dot_references__pb2.GetReferencesRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_references__pb2.GetReferencesResponse.SerializeToString,
            ),
            'SelectProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectProposal,
                    request_deserializer=rewind_dot_v1_dot_references__pb2.SelectProposalRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_references__pb2.SelectProposalResponse.SerializeToString,
            ),
            'UpdateProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProposal,
                    request_deserializer=rewind_dot_v1_dot_references__pb2.UpdateProposalRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_references__pb2.UpdateProposalResponse.SerializeToString,
            ),
            'DeleteProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProposal,
                    request_deserializer=rewind_dot_v1_dot_references__pb2.DeleteProposalRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_references__pb2.DeleteProposalResponse.SerializeToString,
            ),
            'AddProposal': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProposal,
                    request_deserializer=rewind_dot_v1_dot_references__pb2.AddProposalRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_references__pb2.AddProposalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.ReferencesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.ReferencesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReferencesService:
    """ReferencesService is the Gate B surface for the dashboard (SPEC.md 5.3, 8.2).

    The shape mirrors FactsService deliberately: every mutation returns the whole
    recomputed view, because Gate B's rules depend on the sheet as a whole -- how
    many are selected, whether any has expired.
    """

    @staticmethod
    def GetReferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ReferencesService/GetReferences',
            rewind_dot_v1_dot_references__pb2.GetReferencesRequest.SerializeToString,
            rewind_dot_v1_dot_references__pb2.GetReferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ReferencesService/SelectProposal',
            rewind_dot_v1_dot_references__pb2.SelectProposalRequest.SerializeToString,
            rewind_dot_v1_dot_references__pb2.SelectProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ReferencesService/UpdateProposal',
            rewind_dot_v1_dot_references__pb2.UpdateProposalRequest.SerializeToString,
            rewind_dot_v1_dot_references__pb2.UpdateProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ReferencesService/DeleteProposal',
            rewind_dot_v1_dot_references__pb2.DeleteProposalRequest.SerializeToString,
            rewind_dot_v1_dot_references__pb2.DeleteProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProposal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ReferencesService/AddProposal',
            rewind_dot_v1_dot_references__pb2.AddProposalRequest.SerializeToString,
            rewind_dot_v1_dot_references__pb2.AddProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
