"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import relevance_pb2 as _relevance_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RelevanceServiceStub:
    """RelevanceService proposes modern comparisons that make the facts land
    (SPEC.md 5.3).

    Two kinds of reference:

      EVERGREEN -- from a bank you curate (config/reference_bank.yaml). Always
      safe to use, and still funny next year.

      HOT -- scraped from live trend sources today. Funnier now, dead in a
      month, so each carries an expiry that Gate F warns about.

    THE RULE THIS SERVICE MUST NOT BREAK (SPEC.md 5.3, CLAUDE.md): a reference
    compares LOOK, FEELING, PRICE, HYPE or BEHAVIOUR. It never asserts a fact
    about a brand or a person. "Roman caligae were basically Birkenstocks with
    spikes" is a comparison; "Birkenstock was founded in Rome" is a lie.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RelevanceServiceAsyncStub: ...
    ProposeReferences: _grpc.UnaryStreamMultiCallable[_relevance_pb2.ProposeReferencesRequest, _relevance_pb2.ProposeReferencesResponse]
    """ProposeReferences generates comparisons tied to approved facts."""
    ScanTrends: _grpc.UnaryUnaryMultiCallable[_relevance_pb2.ScanTrendsRequest, _relevance_pb2.ScanTrendsResponse]
    """ScanTrends refreshes the cached trend list. Called on a schedule and by
    `rewind doctor`; ProposeReferences uses the cache rather than forcing a
    scan, so a dead trend source never blocks a video.
    """

@_typing.type_check_only
class RelevanceServiceAsyncStub(RelevanceServiceStub):
    """RelevanceService proposes modern comparisons that make the facts land
    (SPEC.md 5.3).

    Two kinds of reference:

      EVERGREEN -- from a bank you curate (config/reference_bank.yaml). Always
      safe to use, and still funny next year.

      HOT -- scraped from live trend sources today. Funnier now, dead in a
      month, so each carries an expiry that Gate F warns about.

    THE RULE THIS SERVICE MUST NOT BREAK (SPEC.md 5.3, CLAUDE.md): a reference
    compares LOOK, FEELING, PRICE, HYPE or BEHAVIOUR. It never asserts a fact
    about a brand or a person. "Roman caligae were basically Birkenstocks with
    spikes" is a comparison; "Birkenstock was founded in Rome" is a lie.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ProposeReferences: _aio.UnaryStreamMultiCallable[_relevance_pb2.ProposeReferencesRequest, _relevance_pb2.ProposeReferencesResponse]  # type: ignore[assignment]
    """ProposeReferences generates comparisons tied to approved facts."""
    ScanTrends: _aio.UnaryUnaryMultiCallable[_relevance_pb2.ScanTrendsRequest, _relevance_pb2.ScanTrendsResponse]  # type: ignore[assignment]
    """ScanTrends refreshes the cached trend list. Called on a schedule and by
    `rewind doctor`; ProposeReferences uses the cache rather than forcing a
    scan, so a dead trend source never blocks a video.
    """

class RelevanceServiceServicer(metaclass=_abc_1.ABCMeta):
    """RelevanceService proposes modern comparisons that make the facts land
    (SPEC.md 5.3).

    Two kinds of reference:

      EVERGREEN -- from a bank you curate (config/reference_bank.yaml). Always
      safe to use, and still funny next year.

      HOT -- scraped from live trend sources today. Funnier now, dead in a
      month, so each carries an expiry that Gate F warns about.

    THE RULE THIS SERVICE MUST NOT BREAK (SPEC.md 5.3, CLAUDE.md): a reference
    compares LOOK, FEELING, PRICE, HYPE or BEHAVIOUR. It never asserts a fact
    about a brand or a person. "Roman caligae were basically Birkenstocks with
    spikes" is a comparison; "Birkenstock was founded in Rome" is a lie.
    """

    @_abc_1.abstractmethod
    def ProposeReferences(
        self,
        request: _relevance_pb2.ProposeReferencesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_relevance_pb2.ProposeReferencesResponse], _abc.AsyncIterator[_relevance_pb2.ProposeReferencesResponse]]:
        """ProposeReferences generates comparisons tied to approved facts."""

    @_abc_1.abstractmethod
    def ScanTrends(
        self,
        request: _relevance_pb2.ScanTrendsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_relevance_pb2.ScanTrendsResponse, _abc.Awaitable[_relevance_pb2.ScanTrendsResponse]]:
        """ScanTrends refreshes the cached trend list. Called on a schedule and by
        `rewind doctor`; ProposeReferences uses the cache rather than forcing a
        scan, so a dead trend source never blocks a video.
        """

def add_RelevanceServiceServicer_to_server(servicer: RelevanceServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
