"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from rewind.v1 import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ReferenceKind:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ReferenceKindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ReferenceKind.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REFERENCE_KIND_UNSPECIFIED: _ReferenceKind.ValueType  # 0
    REFERENCE_KIND_EVERGREEN: _ReferenceKind.ValueType  # 1
    """From config/reference_bank.yaml. No expiry."""
    REFERENCE_KIND_HOT: _ReferenceKind.ValueType  # 2
    """From a live trend source. Expires."""
    REFERENCE_KIND_MANUAL: _ReferenceKind.ValueType  # 3
    """Typed in by the human at Gate B."""

class ReferenceKind(_ReferenceKind, metaclass=_ReferenceKindEnumTypeWrapper):
    """ReferenceKind distinguishes a curated reference from a trending one."""

REFERENCE_KIND_UNSPECIFIED: ReferenceKind.ValueType  # 0
REFERENCE_KIND_EVERGREEN: ReferenceKind.ValueType  # 1
"""From config/reference_bank.yaml. No expiry."""
REFERENCE_KIND_HOT: ReferenceKind.ValueType  # 2
"""From a live trend source. Expires."""
REFERENCE_KIND_MANUAL: ReferenceKind.ValueType  # 3
"""Typed in by the human at Gate B."""
Global___ReferenceKind: _TypeAlias = ReferenceKind  # noqa: Y015

@_typing.final
class ProposeReferencesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    FACTS_FIELD_NUMBER: _builtins.int
    MAX_PROPOSALS_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    topic: _builtins.str
    max_proposals: _builtins.int
    """Ceiling on proposals to generate. The human picks at most
    `max_selectable` of them at Gate B.
    """
    @_builtins.property
    def facts(self) -> _containers.RepeatedCompositeFieldContainer[Global___ApprovedFact]:
        """The APPROVED facts only. A comparison must attach to a fact a human has
        already accepted, or it would smuggle unapproved material into the script.
        """

    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        topic: _builtins.str = ...,
        facts: _abc.Iterable[Global___ApprovedFact] | None = ...,
        max_proposals: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["facts", b"facts", "max_proposals", b"max_proposals", "topic", b"topic", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProposeReferencesRequest: _TypeAlias = ProposeReferencesRequest  # noqa: Y015

@_typing.final
class ApprovedFact(_message.Message):
    """ApprovedFact is the slice of a fact the relevance engine needs. Deliberately
    not the whole Fact: this service has no business with evidence or sources,
    and passing them would invite it to reason about their truth.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    CLAIM_FIELD_NUMBER: _builtins.int
    GROUP_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    label: _builtins.str
    claim: _builtins.str
    group: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        label: _builtins.str = ...,
        claim: _builtins.str = ...,
        group: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim", "group", b"group", "id", b"id", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApprovedFact: _TypeAlias = ApprovedFact  # noqa: Y015

@_typing.final
class ProposeReferencesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROGRESS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def progress(self) -> _common_pb2.Progress: ...
    @_builtins.property
    def result(self) -> Global___ReferenceSheet: ...
    @_builtins.property
    def failure(self) -> _common_pb2.Failure: ...
    def __init__(
        self,
        *,
        progress: _common_pb2.Progress | None = ...,
        result: Global___ReferenceSheet | None = ...,
        failure: _common_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["progress", "result", "failure"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___ProposeReferencesResponse: _TypeAlias = ProposeReferencesResponse  # noqa: Y015

@_typing.final
class Proposal(_message.Message):
    """Proposal is one suggested comparison (SPEC.md 5.3)."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    LINKED_FACT_ID_FIELD_NUMBER: _builtins.int
    COMPARISON_FIELD_NUMBER: _builtins.int
    WHY_FUNNY_FIELD_NUMBER: _builtins.int
    ACCURACY_NOTE_FIELD_NUMBER: _builtins.int
    FRESH_UNTIL_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    SELECTED_FIELD_NUMBER: _builtins.int
    REJECTED_REASON_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """"r1", "r2", ..."""
    reference: _builtins.str
    """The modern thing being compared to: "Birkenstock", "Stanley cup"."""
    kind: Global___ReferenceKind.ValueType
    linked_fact_id: _builtins.str
    """Which approved fact this attaches to. Required: a comparison floating
    free of a fact has nothing to be funny ABOUT.
    """
    comparison: _builtins.str
    """The line itself, as a narrator would say it."""
    why_funny: _builtins.str
    """Why it works, for the human deciding whether it does."""
    accuracy_note: _builtins.str
    """What is being compared -- look, price, hype, behaviour -- stated so a
    reviewer can check it is not a factual claim about the brand.
    """
    fresh_until: _builtins.str
    """For HOT references: the date after which this stops being current.
    Gate F warns if the video is still unpublished by then.
    RFC 3339 date, empty for evergreen
    """
    source: _builtins.str
    """Which trend source produced it, for HOT references."""
    selected: _builtins.bool
    """Set by the human at Gate B; the worker always leaves it false."""
    rejected_reason: _builtins.str
    """Populated when a safety rule rejected this proposal, so the reviewer can
    see WHAT was filtered rather than wondering why the list is short.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        reference: _builtins.str = ...,
        kind: Global___ReferenceKind.ValueType = ...,
        linked_fact_id: _builtins.str = ...,
        comparison: _builtins.str = ...,
        why_funny: _builtins.str = ...,
        accuracy_note: _builtins.str = ...,
        fresh_until: _builtins.str = ...,
        source: _builtins.str = ...,
        selected: _builtins.bool = ...,
        rejected_reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accuracy_note", b"accuracy_note", "comparison", b"comparison", "fresh_until", b"fresh_until", "id", b"id", "kind", b"kind", "linked_fact_id", b"linked_fact_id", "reference", b"reference", "rejected_reason", b"rejected_reason", "selected", b"selected", "source", b"source", "why_funny", b"why_funny"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Proposal: _TypeAlias = Proposal  # noqa: Y015

@_typing.final
class ReferenceSheet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    PROPOSALS_FIELD_NUMBER: _builtins.int
    REFERENCES_JSON_PATH_FIELD_NUMBER: _builtins.int
    CANDIDATES_GENERATED_FIELD_NUMBER: _builtins.int
    CANDIDATES_REJECTED_FIELD_NUMBER: _builtins.int
    REJECTIONS_FIELD_NUMBER: _builtins.int
    MAX_SELECTABLE_FIELD_NUMBER: _builtins.int
    TREND_SOURCES_FIELD_NUMBER: _builtins.int
    TRENDS_FETCHED_AT_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    references_json_path: _builtins.str
    """Where the worker wrote references.json."""
    candidates_generated: _builtins.int
    """How many the model proposed and how many the safety rules threw out --
    the same model-quality signal the fact sheet carries.
    """
    candidates_rejected: _builtins.int
    max_selectable: _builtins.int
    """The maximum a human may select, from config. Carried in the sheet so the
    gate machinery enforces it without a second source of truth.
    """
    trends_fetched_at: _builtins.str
    @_builtins.property
    def proposals(self) -> _containers.RepeatedCompositeFieldContainer[Global___Proposal]: ...
    @_builtins.property
    def rejections(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def trend_sources(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Which trend sources were consulted, and when the cache was last filled."""

    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        proposals: _abc.Iterable[Global___Proposal] | None = ...,
        references_json_path: _builtins.str = ...,
        candidates_generated: _builtins.int = ...,
        candidates_rejected: _builtins.int = ...,
        rejections: _abc.Iterable[_builtins.str] | None = ...,
        max_selectable: _builtins.int = ...,
        trend_sources: _abc.Iterable[_builtins.str] | None = ...,
        trends_fetched_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidates_generated", b"candidates_generated", "candidates_rejected", b"candidates_rejected", "max_selectable", b"max_selectable", "proposals", b"proposals", "references_json_path", b"references_json_path", "rejections", b"rejections", "topic", b"topic", "trend_sources", b"trend_sources", "trends_fetched_at", b"trends_fetched_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReferenceSheet: _TypeAlias = ReferenceSheet  # noqa: Y015

@_typing.final
class ScanTrendsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FORCE_FIELD_NUMBER: _builtins.int
    force: _builtins.bool
    """Refresh even when the cache is still fresh."""
    def __init__(
        self,
        *,
        force: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["force", b"force"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScanTrendsRequest: _TypeAlias = ScanTrendsRequest  # noqa: Y015

@_typing.final
class ScanTrendsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TERM_COUNT_FIELD_NUMBER: _builtins.int
    SOURCES_FIELD_NUMBER: _builtins.int
    FETCHED_AT_FIELD_NUMBER: _builtins.int
    FROM_CACHE_FIELD_NUMBER: _builtins.int
    term_count: _builtins.int
    fetched_at: _builtins.str
    from_cache: _builtins.bool
    @_builtins.property
    def sources(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        term_count: _builtins.int = ...,
        sources: _abc.Iterable[_builtins.str] | None = ...,
        fetched_at: _builtins.str = ...,
        from_cache: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fetched_at", b"fetched_at", "from_cache", b"from_cache", "sources", b"sources", "term_count", b"term_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScanTrendsResponse: _TypeAlias = ScanTrendsResponse  # noqa: Y015
