# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import relevance_pb2 as rewind_dot_v1_dot_relevance__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/relevance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelevanceServiceStub:
    """RelevanceService proposes modern comparisons that make the facts land
    (SPEC.md 5.3).

    Two kinds of reference:

    EVERGREEN -- from a bank you curate (config/reference_bank.yaml). Always
    safe to use, and still funny next year.

    HOT -- scraped from live trend sources today. Funnier now, dead in a
    month, so each carries an expiry that Gate F warns about.

    THE RULE THIS SERVICE MUST NOT BREAK (SPEC.md 5.3, CLAUDE.md): a reference
    compares LOOK, FEELING, PRICE, HYPE or BEHAVIOUR. It never asserts a fact
    about a brand or a person. "Roman caligae were basically Birkenstocks with
    spikes" is a comparison; "Birkenstock was founded in Rome" is a lie.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeReferences = channel.unary_stream(
                '/rewind.v1.RelevanceService/ProposeReferences',
                request_serializer=rewind_dot_v1_dot_relevance__pb2.ProposeReferencesRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_relevance__pb2.ProposeReferencesResponse.FromString,
                _registered_method=True)
        self.ScanTrends = channel.unary_unary(
                '/rewind.v1.RelevanceService/ScanTrends',
                request_serializer=rewind_dot_v1_dot_relevance__pb2.ScanTrendsRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_relevance__pb2.ScanTrendsResponse.FromString,
                _registered_method=True)


class RelevanceServiceServicer:
    """RelevanceService proposes modern comparisons that make the facts land
    (SPEC.md 5.3).

    Two kinds of reference:

    EVERGREEN -- from a bank you curate (config/reference_bank.yaml). Always
    safe to use, and still funny next year.

    HOT -- scraped from live trend sources today. Funnier now, dead in a
    month, so each carries an expiry that Gate F warns about.

    THE RULE THIS SERVICE MUST NOT BREAK (SPEC.md 5.3, CLAUDE.md): a reference
    compares LOOK, FEELING, PRICE, HYPE or BEHAVIOUR. It never asserts a fact
    about a brand or a person. "Roman caligae were basically Birkenstocks with
    spikes" is a comparison; "Birkenstock was founded in Rome" is a lie.
    """

    def ProposeReferences(self, request, context):
        """ProposeReferences generates comparisons tied to approved facts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanTrends(self, request, context):
        """ScanTrends refreshes the cached trend list. Called on a schedule and by
        `rewind doctor`; ProposeReferences uses the cache rather than forcing a
        scan, so a dead trend source never blocks a video.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelevanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeReferences': grpc.unary_stream_rpc_method_handler(
                    servicer.ProposeReferences,
                    request_deserializer=rewind_dot_v1_dot_relevance__pb2.ProposeReferencesRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_relevance__pb2.ProposeReferencesResponse.SerializeToString,
            ),
            'ScanTrends': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanTrends,
                    request_deserializer=rewind_dot_v1_dot_relevance__pb2.ScanTrendsRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_relevance__pb2.ScanTrendsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.RelevanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.RelevanceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelevanceService:
    """RelevanceService proposes modern comparisons that make the facts land
    (SPEC.md 5.3).

    Two kinds of reference:

    EVERGREEN -- from a bank you curate (config/reference_bank.yaml). Always
    safe to use, and still funny next year.

    HOT -- scraped from live trend sources today. Funnier now, dead in a
    month, so each carries an expiry that Gate F warns about.

    THE RULE THIS SERVICE MUST NOT BREAK (SPEC.md 5.3, CLAUDE.md): a reference
    compares LOOK, FEELING, PRICE, HYPE or BEHAVIOUR. It never asserts a fact
    about a brand or a person. "Roman caligae were basically Birkenstocks with
    spikes" is a comparison; "Birkenstock was founded in Rome" is a lie.
    """

    @staticmethod
    def ProposeReferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rewind.v1.RelevanceService/ProposeReferences',
            rewind_dot_v1_dot_relevance__pb2.ProposeReferencesRequest.SerializeToString,
            rewind_dot_v1_dot_relevance__pb2.ProposeReferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanTrends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.RelevanceService/ScanTrends',
            rewind_dot_v1_dot_relevance__pb2.ScanTrendsRequest.SerializeToString,
            rewind_dot_v1_dot_relevance__pb2.ScanTrendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
