# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import research_pb2 as rewind_dot_v1_dot_research__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/research_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResearchServiceStub:
    """ResearchService builds a timeline of true, sourced facts (SPEC.md 5.2).

    The rule this service exists to enforce: THE LLM IS NEVER THE SOURCE OF A
    FACT. It only extracts from text that was fetched, and every extraction must
    carry the exact sentence it came from. A verifier then checks that sentence
    really appears in the fetched source, and drops anything that does not.
    That is what makes hallucinated dates impossible rather than unlikely.
    The format -- timeline, myth-buster, ranked list -- is chosen in
    config/channel.yaml and owned entirely by the worker. Go never needs to know
    which formats exist: the fact sheet declares its own review thresholds, so
    the gate machinery works for a format written after this comment.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildFactSheet = channel.unary_stream(
                '/rewind.v1.ResearchService/BuildFactSheet',
                request_serializer=rewind_dot_v1_dot_research__pb2.BuildFactSheetRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_research__pb2.BuildFactSheetResponse.FromString,
                _registered_method=True)


class ResearchServiceServicer:
    """ResearchService builds a timeline of true, sourced facts (SPEC.md 5.2).

    The rule this service exists to enforce: THE LLM IS NEVER THE SOURCE OF A
    FACT. It only extracts from text that was fetched, and every extraction must
    carry the exact sentence it came from. A verifier then checks that sentence
    really appears in the fetched source, and drops anything that does not.
    That is what makes hallucinated dates impossible rather than unlikely.
    The format -- timeline, myth-buster, ranked list -- is chosen in
    config/channel.yaml and owned entirely by the worker. Go never needs to know
    which formats exist: the fact sheet declares its own review thresholds, so
    the gate machinery works for a format written after this comment.
    """

    def BuildFactSheet(self, request, context):
        """BuildFactSheet researches a topic.

        Server-streaming: research takes minutes, so progress events flow while it
        works and one terminal message ends it (SPEC.md 2.5).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildFactSheet': grpc.unary_stream_rpc_method_handler(
                    servicer.BuildFactSheet,
                    request_deserializer=rewind_dot_v1_dot_research__pb2.BuildFactSheetRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_research__pb2.BuildFactSheetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.ResearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.ResearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResearchService:
    """ResearchService builds a timeline of true, sourced facts (SPEC.md 5.2).

    The rule this service exists to enforce: THE LLM IS NEVER THE SOURCE OF A
    FACT. It only extracts from text that was fetched, and every extraction must
    carry the exact sentence it came from. A verifier then checks that sentence
    really appears in the fetched source, and drops anything that does not.
    That is what makes hallucinated dates impossible rather than unlikely.
    The format -- timeline, myth-buster, ranked list -- is chosen in
    config/channel.yaml and owned entirely by the worker. Go never needs to know
    which formats exist: the fact sheet declares its own review thresholds, so
    the gate machinery works for a format written after this comment.
    """

    @staticmethod
    def BuildFactSheet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rewind.v1.ResearchService/BuildFactSheet',
            rewind_dot_v1_dot_research__pb2.BuildFactSheetRequest.SerializeToString,
            rewind_dot_v1_dot_research__pb2.BuildFactSheetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
