"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import research_pb2 as _research_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ResearchServiceStub:
    """ResearchService builds a timeline of true, sourced facts (SPEC.md 5.2).

    The rule this service exists to enforce: THE LLM IS NEVER THE SOURCE OF A
    FACT. It only extracts from text that was fetched, and every extraction must
    carry the exact sentence it came from. A verifier then checks that sentence
    really appears in the fetched source, and drops anything that does not.
    That is what makes hallucinated dates impossible rather than unlikely.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ResearchServiceAsyncStub: ...
    BuildFactSheet: _grpc.UnaryStreamMultiCallable[_research_pb2.BuildFactSheetRequest, _research_pb2.BuildFactSheetResponse]
    """BuildFactSheet researches a topic.

    Server-streaming: research takes minutes, so progress events flow while it
    works and one terminal message ends it (SPEC.md 2.5).
    """

@_typing.type_check_only
class ResearchServiceAsyncStub(ResearchServiceStub):
    """ResearchService builds a timeline of true, sourced facts (SPEC.md 5.2).

    The rule this service exists to enforce: THE LLM IS NEVER THE SOURCE OF A
    FACT. It only extracts from text that was fetched, and every extraction must
    carry the exact sentence it came from. A verifier then checks that sentence
    really appears in the fetched source, and drops anything that does not.
    That is what makes hallucinated dates impossible rather than unlikely.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    BuildFactSheet: _aio.UnaryStreamMultiCallable[_research_pb2.BuildFactSheetRequest, _research_pb2.BuildFactSheetResponse]  # type: ignore[assignment]
    """BuildFactSheet researches a topic.

    Server-streaming: research takes minutes, so progress events flow while it
    works and one terminal message ends it (SPEC.md 2.5).
    """

class ResearchServiceServicer(metaclass=_abc_1.ABCMeta):
    """ResearchService builds a timeline of true, sourced facts (SPEC.md 5.2).

    The rule this service exists to enforce: THE LLM IS NEVER THE SOURCE OF A
    FACT. It only extracts from text that was fetched, and every extraction must
    carry the exact sentence it came from. A verifier then checks that sentence
    really appears in the fetched source, and drops anything that does not.
    That is what makes hallucinated dates impossible rather than unlikely.
    """

    @_abc_1.abstractmethod
    def BuildFactSheet(
        self,
        request: _research_pb2.BuildFactSheetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_research_pb2.BuildFactSheetResponse], _abc.AsyncIterator[_research_pb2.BuildFactSheetResponse]]:
        """BuildFactSheet researches a topic.

        Server-streaming: research takes minutes, so progress events flow while it
        works and one terminal message ends it (SPEC.md 2.5).
        """

def add_ResearchServiceServicer_to_server(servicer: ResearchServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
