"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from rewind.v1 import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BuildFactSheetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    EXTRA_URLS_FIELD_NUMBER: _builtins.int
    MIN_FACTS_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    """Go's id. The worker uses it only to choose the output folder."""
    topic: _builtins.str
    min_facts: _builtins.int
    """Below this many verified facts the worker reports failure rather than
    handing over a fact sheet too thin to review.
    """
    @_builtins.property
    def extra_urls(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Extra URLs supplied by the human, fetched alongside Wikipedia."""

    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        topic: _builtins.str = ...,
        extra_urls: _abc.Iterable[_builtins.str] | None = ...,
        min_facts: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extra_urls", b"extra_urls", "min_facts", b"min_facts", "topic", b"topic", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BuildFactSheetRequest: _TypeAlias = BuildFactSheetRequest  # noqa: Y015

@_typing.final
class BuildFactSheetResponse(_message.Message):
    """One streamed event: repeated progress, then exactly one terminal
    result or failure.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PROGRESS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def progress(self) -> _common_pb2.Progress: ...
    @_builtins.property
    def result(self) -> Global___FactSheet: ...
    @_builtins.property
    def failure(self) -> _common_pb2.Failure: ...
    def __init__(
        self,
        *,
        progress: _common_pb2.Progress | None = ...,
        result: Global___FactSheet | None = ...,
        failure: _common_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["progress", "result", "failure"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___BuildFactSheetResponse: _TypeAlias = BuildFactSheetResponse  # noqa: Y015

@_typing.final
class Fact(_message.Message):
    """Fact is one timeline entry (SPEC.md 5.2)."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    YEAR_LABEL_FIELD_NUMBER: _builtins.int
    SORT_YEAR_FIELD_NUMBER: _builtins.int
    PLACE_FIELD_NUMBER: _builtins.int
    CLAIM_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    SOURCE_TITLE_FIELD_NUMBER: _builtins.int
    CONFIDENCE_FIELD_NUMBER: _builtins.int
    CONFLICT_FIELD_NUMBER: _builtins.int
    APPROVED_FIELD_NUMBER: _builtins.int
    MATCH_SCORE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """"f1", "f2", ..."""
    year_label: _builtins.str
    """How the year is spoken, e.g. "~9,000 years ago" or "1882"."""
    sort_year: _builtins.int
    """Sortable year; negative for BC. -7000 means 7000 BC."""
    place: _builtins.str
    claim: _builtins.str
    """The claim, in the narrator's words."""
    evidence: _builtins.str
    """The EXACT sentence from the source that supports the claim. The verifier
    checks this appears in the fetched text; a fact whose evidence cannot be
    found is dropped before a human ever sees it.
    """
    source_url: _builtins.str
    source_title: _builtins.str
    """Title of the source, for display next to the link."""
    confidence: _builtins.str
    """"high" | "medium" | "low", from how directly the evidence supports it."""
    conflict: _builtins.bool
    """True when sources disagree about this fact."""
    approved: _builtins.bool
    """Set by the human at Gate A; the worker always leaves it unset."""
    match_score: _builtins.float
    """How closely the evidence matched the source, 0..1. Surfaced at Gate A so
    a borderline match can be eyeballed.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        year_label: _builtins.str = ...,
        sort_year: _builtins.int = ...,
        place: _builtins.str = ...,
        claim: _builtins.str = ...,
        evidence: _builtins.str = ...,
        source_url: _builtins.str = ...,
        source_title: _builtins.str = ...,
        confidence: _builtins.str = ...,
        conflict: _builtins.bool = ...,
        approved: _builtins.bool = ...,
        match_score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approved", b"approved", "claim", b"claim", "confidence", b"confidence", "conflict", b"conflict", "evidence", b"evidence", "id", b"id", "match_score", b"match_score", "place", b"place", "sort_year", b"sort_year", "source_title", b"source_title", "source_url", b"source_url", "year_label", b"year_label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fact: _TypeAlias = Fact  # noqa: Y015

@_typing.final
class SourceDocument(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    FETCHER_FIELD_NUMBER: _builtins.int
    CHAR_COUNT_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    title: _builtins.str
    fetcher: _builtins.str
    """Which fetcher produced it: "wikipedia", "user_url", ..."""
    char_count: _builtins.int
    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        title: _builtins.str = ...,
        fetcher: _builtins.str = ...,
        char_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["char_count", b"char_count", "fetcher", b"fetcher", "title", b"title", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SourceDocument: _TypeAlias = SourceDocument  # noqa: Y015

@_typing.final
class FactSheet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    FACTS_FIELD_NUMBER: _builtins.int
    SOURCES_FIELD_NUMBER: _builtins.int
    FACTS_JSON_PATH_FIELD_NUMBER: _builtins.int
    CANDIDATES_EXTRACTED_FIELD_NUMBER: _builtins.int
    CANDIDATES_REJECTED_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    facts_json_path: _builtins.str
    """Where the worker wrote facts.json. Paths, not bytes (SPEC.md 2.5)."""
    candidates_extracted: _builtins.int
    """How many candidates the LLM proposed and how many survived verification.
    Shown at Gate A: a large gap is a signal the model is drifting, and worth
    knowing before you trust what is left.
    """
    candidates_rejected: _builtins.int
    @_builtins.property
    def facts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Fact]: ...
    @_builtins.property
    def sources(self) -> _containers.RepeatedCompositeFieldContainer[Global___SourceDocument]: ...
    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        facts: _abc.Iterable[Global___Fact] | None = ...,
        sources: _abc.Iterable[Global___SourceDocument] | None = ...,
        facts_json_path: _builtins.str = ...,
        candidates_extracted: _builtins.int = ...,
        candidates_rejected: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidates_extracted", b"candidates_extracted", "candidates_rejected", b"candidates_rejected", "facts", b"facts", "facts_json_path", b"facts_json_path", "sources", b"sources", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FactSheet: _TypeAlias = FactSheet  # noqa: Y015
