"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from rewind.v1 import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BuildFactSheetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    EXTRA_URLS_FIELD_NUMBER: _builtins.int
    MIN_FACTS_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    """Go's id. The worker uses it only to choose the output folder."""
    topic: _builtins.str
    min_facts: _builtins.int
    """Below this many verified facts the worker reports failure rather than
    handing over a fact sheet too thin to review.
    """
    @_builtins.property
    def extra_urls(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Extra URLs supplied by the human, fetched alongside Wikipedia."""

    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        topic: _builtins.str = ...,
        extra_urls: _abc.Iterable[_builtins.str] | None = ...,
        min_facts: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extra_urls", b"extra_urls", "min_facts", b"min_facts", "topic", b"topic", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BuildFactSheetRequest: _TypeAlias = BuildFactSheetRequest  # noqa: Y015

@_typing.final
class BuildFactSheetResponse(_message.Message):
    """One streamed event: repeated progress, then exactly one terminal
    result or failure.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PROGRESS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def progress(self) -> _common_pb2.Progress: ...
    @_builtins.property
    def result(self) -> Global___FactSheet: ...
    @_builtins.property
    def failure(self) -> _common_pb2.Failure: ...
    def __init__(
        self,
        *,
        progress: _common_pb2.Progress | None = ...,
        result: Global___FactSheet | None = ...,
        failure: _common_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["progress", "result", "failure"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___BuildFactSheetResponse: _TypeAlias = BuildFactSheetResponse  # noqa: Y015

@_typing.final
class Fact(_message.Message):
    """Fact is one verified item (SPEC.md 5.2).

    The field names are format-neutral on purpose. For a timeline, `label` is a
    year and `sort_key` orders chronologically; for a myth-buster, `label` is
    the belief and `sort_key` is how surprising the correction is. What never
    varies is the pairing of `claim` with the `evidence` that supports it.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    SORT_KEY_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    CLAIM_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    SOURCE_TITLE_FIELD_NUMBER: _builtins.int
    CONFIDENCE_FIELD_NUMBER: _builtins.int
    CONFLICT_FIELD_NUMBER: _builtins.int
    APPROVED_FIELD_NUMBER: _builtins.int
    MATCH_SCORE_FIELD_NUMBER: _builtins.int
    GROUP_FIELD_NUMBER: _builtins.int
    ADDED_BY_HUMAN_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """"f1", "f2", ..."""
    label: _builtins.str
    """What the narrator says to introduce this item.
    Timeline: "~9,000 years ago". Myth-buster: "You need 8 hours of sleep".
    """
    sort_key: _builtins.int
    """Orders the items. Meaning is the format's: a year (negative for BC), a
    rank, a step number, a surprise rating.

    int64, not int32: asked about "iron", a model correctly returns the
    formation of the Earth's core at -4,600,000,000, which overflows int32 and
    used to crash serialization AFTER all the research work was done. Such a
    value is rejected on plausibility grounds by the format -- but that is a
    decision for the pipeline to make and report, never a failure mode of the
    wire format.
    """
    context: _builtins.str
    """Where or in what setting. Timeline: "Oregon, USA". Myth-buster: "health"."""
    claim: _builtins.str
    """The claim, in the narrator's words."""
    evidence: _builtins.str
    """The EXACT sentence from the source that supports the claim. The verifier
    checks this appears in the fetched text; a fact whose evidence cannot be
    found is dropped before a human ever sees it.
    """
    source_url: _builtins.str
    source_title: _builtins.str
    """Title of the source, for display next to the link."""
    confidence: _builtins.str
    """"high" | "medium" | "low", from how directly the evidence supports it."""
    conflict: _builtins.bool
    """True when sources disagree about this fact."""
    approved: _builtins.bool
    """Set by the human at Gate A; the worker always leaves it unset."""
    match_score: _builtins.float
    """How closely the evidence matched the source, 0..1. Surfaced at Gate A so
    a borderline match can be eyeballed.
    """
    group: _builtins.str
    """The variety bucket this item falls in, computed by the format.
    Timeline: "industrial". Myth-buster: "health". Gate A requires the
    approved items to span several distinct groups, so a video is not eight
    variations on one idea.
    """
    added_by_human: _builtins.bool
    """True for items a human typed in themselves at the gate. Those skip the
    evidence verifier -- a person citing a book is the authority the verifier
    substitutes for -- so it matters that they stay distinguishable.
    """
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        label: _builtins.str = ...,
        sort_key: _builtins.int = ...,
        context: _builtins.str = ...,
        claim: _builtins.str = ...,
        evidence: _builtins.str = ...,
        source_url: _builtins.str = ...,
        source_title: _builtins.str = ...,
        confidence: _builtins.str = ...,
        conflict: _builtins.bool = ...,
        approved: _builtins.bool = ...,
        match_score: _builtins.float = ...,
        group: _builtins.str = ...,
        added_by_human: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["added_by_human", b"added_by_human", "approved", b"approved", "claim", b"claim", "confidence", b"confidence", "conflict", b"conflict", "context", b"context", "evidence", b"evidence", "group", b"group", "id", b"id", "label", b"label", "match_score", b"match_score", "sort_key", b"sort_key", "source_title", b"source_title", "source_url", b"source_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Fact: _TypeAlias = Fact  # noqa: Y015

@_typing.final
class SourceDocument(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    FETCHER_FIELD_NUMBER: _builtins.int
    CHAR_COUNT_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    title: _builtins.str
    fetcher: _builtins.str
    """Which fetcher produced it: "wikipedia", "user_url", ..."""
    char_count: _builtins.int
    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        title: _builtins.str = ...,
        fetcher: _builtins.str = ...,
        char_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["char_count", b"char_count", "fetcher", b"fetcher", "title", b"title", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SourceDocument: _TypeAlias = SourceDocument  # noqa: Y015

@_typing.final
class FactSheet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    FACTS_FIELD_NUMBER: _builtins.int
    SOURCES_FIELD_NUMBER: _builtins.int
    FACTS_JSON_PATH_FIELD_NUMBER: _builtins.int
    CANDIDATES_EXTRACTED_FIELD_NUMBER: _builtins.int
    CANDIDATES_REJECTED_FIELD_NUMBER: _builtins.int
    REJECTIONS_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    GROUP_NOUN_FIELD_NUMBER: _builtins.int
    MIN_ITEMS_FIELD_NUMBER: _builtins.int
    MIN_GROUPS_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    facts_json_path: _builtins.str
    """Where the worker wrote facts.json. Paths, not bytes (SPEC.md 2.5)."""
    candidates_extracted: _builtins.int
    """How many candidates the LLM proposed and how many were thrown out.
    Shown at Gate A: a large gap is a measurement of the MODEL, not of the
    topic -- the one objective signal of how much a given model invents on
    this exact task.
    """
    candidates_rejected: _builtins.int
    format: _builtins.str
    """Which content format produced this sheet, and the words to describe its
    variety requirement. Carried in the sheet so the gate machinery can
    enforce a format's rules without knowing the format exists.
    """
    group_noun: _builtins.str
    """"era", "domain", "category" """
    min_items: _builtins.int
    """The thresholds this sheet's format requires before its gate can open."""
    min_groups: _builtins.int
    @_builtins.property
    def facts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Fact]: ...
    @_builtins.property
    def sources(self) -> _containers.RepeatedCompositeFieldContainer[Global___SourceDocument]: ...
    @_builtins.property
    def rejections(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Why each one was thrown out, so the number is inspectable rather than
        merely alarming.
        """

    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        facts: _abc.Iterable[Global___Fact] | None = ...,
        sources: _abc.Iterable[Global___SourceDocument] | None = ...,
        facts_json_path: _builtins.str = ...,
        candidates_extracted: _builtins.int = ...,
        candidates_rejected: _builtins.int = ...,
        rejections: _abc.Iterable[_builtins.str] | None = ...,
        format: _builtins.str = ...,
        group_noun: _builtins.str = ...,
        min_items: _builtins.int = ...,
        min_groups: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidates_extracted", b"candidates_extracted", "candidates_rejected", b"candidates_rejected", "facts", b"facts", "facts_json_path", b"facts_json_path", "format", b"format", "group_noun", b"group_noun", "min_groups", b"min_groups", "min_items", b"min_items", "rejections", b"rejections", "sources", b"sources", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FactSheet: _TypeAlias = FactSheet  # noqa: Y015
