"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from rewind.v1 import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ScriptFact(_message.Message):
    """ScriptFact is an approved fact as the script writer sees it. Unlike the
    relevance engine, the script DOES get the evidence: a beat may use a number
    that is in the quote even if the one-line claim left it out.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    CLAIM_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    SOURCE_URL_FIELD_NUMBER: _builtins.int
    GROUP_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    label: _builtins.str
    claim: _builtins.str
    evidence: _builtins.str
    context: _builtins.str
    source_url: _builtins.str
    group: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        label: _builtins.str = ...,
        claim: _builtins.str = ...,
        evidence: _builtins.str = ...,
        context: _builtins.str = ...,
        source_url: _builtins.str = ...,
        group: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claim", b"claim", "context", b"context", "evidence", b"evidence", "group", b"group", "id", b"id", "label", b"label", "source_url", b"source_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScriptFact: _TypeAlias = ScriptFact  # noqa: Y015

@_typing.final
class ScriptReference(_message.Message):
    """ScriptReference is a comparison selected at Gate B."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    REFERENCE_FIELD_NUMBER: _builtins.int
    COMPARISON_FIELD_NUMBER: _builtins.int
    LINKED_FACT_ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    reference: _builtins.str
    comparison: _builtins.str
    linked_fact_id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        reference: _builtins.str = ...,
        comparison: _builtins.str = ...,
        linked_fact_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comparison", b"comparison", "id", b"id", "linked_fact_id", b"linked_fact_id", "reference", b"reference"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScriptReference: _TypeAlias = ScriptReference  # noqa: Y015

@_typing.final
class GenerateScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    ANGLE_FIELD_NUMBER: _builtins.int
    FACTS_FIELD_NUMBER: _builtins.int
    REFERENCES_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    topic: _builtins.str
    angle: _builtins.str
    """The optional angle typed with the topic: "focus on how ugly they were".
    Steers tone and emphasis ONLY. It is never a source of facts.
    """
    @_builtins.property
    def facts(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptFact]:
        """Approved facts only."""

    @_builtins.property
    def references(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptReference]:
        """Selected comparisons only. May be empty: a straight history video."""

    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        topic: _builtins.str = ...,
        angle: _builtins.str = ...,
        facts: _abc.Iterable[Global___ScriptFact] | None = ...,
        references: _abc.Iterable[Global___ScriptReference] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["angle", b"angle", "facts", b"facts", "references", b"references", "topic", b"topic", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GenerateScriptRequest: _TypeAlias = GenerateScriptRequest  # noqa: Y015

@_typing.final
class GenerateScriptResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROGRESS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def progress(self) -> _common_pb2.Progress: ...
    @_builtins.property
    def result(self) -> Global___Script: ...
    @_builtins.property
    def failure(self) -> _common_pb2.Failure: ...
    def __init__(
        self,
        *,
        progress: _common_pb2.Progress | None = ...,
        result: Global___Script | None = ...,
        failure: _common_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "failure", b"failure", "progress", b"progress", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_event: _TypeAlias = _typing.Literal["progress", "result", "failure"]  # noqa: Y015
    _WhichOneofArgType_event: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_event) -> _WhichOneofReturnType_event | None: ...

Global___GenerateScriptResponse: _TypeAlias = GenerateScriptResponse  # noqa: Y015

@_typing.final
class Beat(_message.Message):
    """Beat is one ~5 second unit of the video (SPEC.md 5.4)."""

    DESCRIPTOR: _descriptor.Descriptor

    N_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    YEAR_STAMP_FIELD_NUMBER: _builtins.int
    VOICE_FIELD_NUMBER: _builtins.int
    ON_SCREEN_TEXT_FIELD_NUMBER: _builtins.int
    VISUAL_PROMPTS_FIELD_NUMBER: _builtins.int
    SFX_FIELD_NUMBER: _builtins.int
    MOTION_FIELD_NUMBER: _builtins.int
    EMPHASIS_WORDS_FIELD_NUMBER: _builtins.int
    FACT_IDS_FIELD_NUMBER: _builtins.int
    REF_IDS_FIELD_NUMBER: _builtins.int
    IS_PUNCH_FIELD_NUMBER: _builtins.int
    n: _builtins.int
    role: _builtins.str
    """Declared by the content format: "hook", "era", "rehook", "today" for a
    timeline. A string rather than an enum because formats differ.
    """
    year_stamp: _builtins.str
    """The date shown on screen, e.g. "~7000 BC". Empty for beats without one."""
    voice: _builtins.str
    """What the narrator says. Numbers are DIGITS ("9,000 years"), so they can
    be checked; turning them into speech is Module 5's job.
    """
    on_screen_text: _builtins.str
    sfx: _builtins.str
    motion: _builtins.str
    is_punch: _builtins.bool
    @_builtins.property
    def visual_prompts(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def emphasis_words(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def fact_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The approved facts this beat states. Every number in the beat must come
        from one of these.
        """

    @_builtins.property
    def ref_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The selected comparisons this beat uses."""

    def __init__(
        self,
        *,
        n: _builtins.int = ...,
        role: _builtins.str = ...,
        year_stamp: _builtins.str = ...,
        voice: _builtins.str = ...,
        on_screen_text: _builtins.str = ...,
        visual_prompts: _abc.Iterable[_builtins.str] | None = ...,
        sfx: _builtins.str = ...,
        motion: _builtins.str = ...,
        emphasis_words: _abc.Iterable[_builtins.str] | None = ...,
        fact_ids: _abc.Iterable[_builtins.str] | None = ...,
        ref_ids: _abc.Iterable[_builtins.str] | None = ...,
        is_punch: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emphasis_words", b"emphasis_words", "fact_ids", b"fact_ids", "is_punch", b"is_punch", "motion", b"motion", "n", b"n", "on_screen_text", b"on_screen_text", "ref_ids", b"ref_ids", "role", b"role", "sfx", b"sfx", "visual_prompts", b"visual_prompts", "voice", b"voice", "year_stamp", b"year_stamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Beat: _TypeAlias = Beat  # noqa: Y015

@_typing.final
class Violation(_message.Message):
    """Violation is one broken rule. `rule` is a stable code the dashboard and
    tests can key on; `message` is for the human.
    """

    DESCRIPTOR: _descriptor.Descriptor

    RULE_FIELD_NUMBER: _builtins.int
    BEAT_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    rule: _builtins.str
    beat: _builtins.int
    """The beat it is in, 1-based; 0 for the script as a whole."""
    message: _builtins.str
    def __init__(
        self,
        *,
        rule: _builtins.str = ...,
        beat: _builtins.int = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["beat", b"beat", "message", b"message", "rule", b"rule"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Violation: _TypeAlias = Violation  # noqa: Y015

@_typing.final
class Script(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_OPTIONS_FIELD_NUMBER: _builtins.int
    CHOSEN_TITLE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    HASHTAGS_FIELD_NUMBER: _builtins.int
    BEATS_FIELD_NUMBER: _builtins.int
    SOURCES_FIELD_NUMBER: _builtins.int
    SCRIPT_JSON_PATH_FIELD_NUMBER: _builtins.int
    ATTEMPTS_FIELD_NUMBER: _builtins.int
    VIOLATIONS_FIELD_NUMBER: _builtins.int
    chosen_title: _builtins.str
    """Picked by the human at Gate C. Empty until then."""
    description: _builtins.str
    script_json_path: _builtins.str
    attempts: _builtins.int
    """How many generations it took to pass validation."""
    @_builtins.property
    def title_options(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def hashtags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def beats(self) -> _containers.RepeatedCompositeFieldContainer[Global___Beat]: ...
    @_builtins.property
    def sources(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Source URLs of the facts used, built from the facts -- never written by
        the model.
        """

    @_builtins.property
    def violations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Violation]:
        """What is still wrong. Empty when the script is valid."""

    def __init__(
        self,
        *,
        title_options: _abc.Iterable[_builtins.str] | None = ...,
        chosen_title: _builtins.str = ...,
        description: _builtins.str = ...,
        hashtags: _abc.Iterable[_builtins.str] | None = ...,
        beats: _abc.Iterable[Global___Beat] | None = ...,
        sources: _abc.Iterable[_builtins.str] | None = ...,
        script_json_path: _builtins.str = ...,
        attempts: _builtins.int = ...,
        violations: _abc.Iterable[Global___Violation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attempts", b"attempts", "beats", b"beats", "chosen_title", b"chosen_title", "description", b"description", "hashtags", b"hashtags", "script_json_path", b"script_json_path", "sources", b"sources", "title_options", b"title_options", "violations", b"violations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Script: _TypeAlias = Script  # noqa: Y015

@_typing.final
class ValidateScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_FIELD_NUMBER: _builtins.int
    FACTS_FIELD_NUMBER: _builtins.int
    REFERENCES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def script(self) -> Global___Script: ...
    @_builtins.property
    def facts(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptFact]: ...
    @_builtins.property
    def references(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptReference]: ...
    def __init__(
        self,
        *,
        script: Global___Script | None = ...,
        facts: _abc.Iterable[Global___ScriptFact] | None = ...,
        references: _abc.Iterable[Global___ScriptReference] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["script", b"script"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["facts", b"facts", "references", b"references", "script", b"script"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateScriptRequest: _TypeAlias = ValidateScriptRequest  # noqa: Y015

@_typing.final
class ValidateScriptResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIOLATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def violations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Violation]: ...
    def __init__(
        self,
        *,
        violations: _abc.Iterable[Global___Violation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["violations", b"violations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidateScriptResponse: _TypeAlias = ValidateScriptResponse  # noqa: Y015
