"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import scripts_pb2 as _scripts_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ScriptsServiceStub:
    """ScriptsService is the Gate C surface for the dashboard (SPEC.md 5.4, 8.2).

    Like the other gate services, every mutation returns the whole recomputed
    view. An edit is saved, then re-validated by the worker's rules before the
    view comes back, so the dashboard always shows what is wrong NOW.

    Regenerating the whole script is not here: that is "send back" on the gate
    (VideoService.RejectGate), which reruns the script step and logs why.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ScriptsServiceAsyncStub: ...
    GetScript: _grpc.UnaryUnaryMultiCallable[_scripts_pb2.GetScriptRequest, _scripts_pb2.GetScriptResponse]
    UpdateBeat: _grpc.UnaryUnaryMultiCallable[_scripts_pb2.UpdateBeatRequest, _scripts_pb2.UpdateBeatResponse]
    """UpdateBeat rewrites what one beat says or shows."""
    ChooseTitle: _grpc.UnaryUnaryMultiCallable[_scripts_pb2.ChooseTitleRequest, _scripts_pb2.ChooseTitleResponse]
    """ChooseTitle picks one of the title options, or a title typed in full."""

@_typing.type_check_only
class ScriptsServiceAsyncStub(ScriptsServiceStub):
    """ScriptsService is the Gate C surface for the dashboard (SPEC.md 5.4, 8.2).

    Like the other gate services, every mutation returns the whole recomputed
    view. An edit is saved, then re-validated by the worker's rules before the
    view comes back, so the dashboard always shows what is wrong NOW.

    Regenerating the whole script is not here: that is "send back" on the gate
    (VideoService.RejectGate), which reruns the script step and logs why.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetScript: _aio.UnaryUnaryMultiCallable[_scripts_pb2.GetScriptRequest, _scripts_pb2.GetScriptResponse]  # type: ignore[assignment]
    UpdateBeat: _aio.UnaryUnaryMultiCallable[_scripts_pb2.UpdateBeatRequest, _scripts_pb2.UpdateBeatResponse]  # type: ignore[assignment]
    """UpdateBeat rewrites what one beat says or shows."""
    ChooseTitle: _aio.UnaryUnaryMultiCallable[_scripts_pb2.ChooseTitleRequest, _scripts_pb2.ChooseTitleResponse]  # type: ignore[assignment]
    """ChooseTitle picks one of the title options, or a title typed in full."""

class ScriptsServiceServicer(metaclass=_abc_1.ABCMeta):
    """ScriptsService is the Gate C surface for the dashboard (SPEC.md 5.4, 8.2).

    Like the other gate services, every mutation returns the whole recomputed
    view. An edit is saved, then re-validated by the worker's rules before the
    view comes back, so the dashboard always shows what is wrong NOW.

    Regenerating the whole script is not here: that is "send back" on the gate
    (VideoService.RejectGate), which reruns the script step and logs why.
    """

    @_abc_1.abstractmethod
    def GetScript(
        self,
        request: _scripts_pb2.GetScriptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_scripts_pb2.GetScriptResponse, _abc.Awaitable[_scripts_pb2.GetScriptResponse]]: ...

    @_abc_1.abstractmethod
    def UpdateBeat(
        self,
        request: _scripts_pb2.UpdateBeatRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_scripts_pb2.UpdateBeatResponse, _abc.Awaitable[_scripts_pb2.UpdateBeatResponse]]:
        """UpdateBeat rewrites what one beat says or shows."""

    @_abc_1.abstractmethod
    def ChooseTitle(
        self,
        request: _scripts_pb2.ChooseTitleRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_scripts_pb2.ChooseTitleResponse, _abc.Awaitable[_scripts_pb2.ChooseTitleResponse]]:
        """ChooseTitle picks one of the title options, or a title typed in full."""

def add_ScriptsServiceServicer_to_server(servicer: ScriptsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
