# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rewind/v1/scripts.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rewind/v1/scripts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rewind.v1 import script_pb2 as rewind_dot_v1_dot_script__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rewind/v1/scripts.proto\x12\trewind.v1\x1a\x16rewind/v1/script.proto\"n\n\nScriptView\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12!\n\x06script\x18\x02 \x01(\x0b\x32\x11.rewind.v1.Script\x12\x13\n\x0b\x63\x61n_approve\x18\x03 \x01(\x08\x12\x18\n\x10\x61pproval_blocker\x18\x04 \x01(\t\"$\n\x10GetScriptRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"8\n\x11GetScriptResponse\x12#\n\x04view\x18\x01 \x01(\x0b\x32\x15.rewind.v1.ScriptView\"|\n\x11UpdateBeatRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\x05\x12\r\n\x05voice\x18\x03 \x01(\t\x12\x16\n\x0eon_screen_text\x18\x04 \x01(\t\x12\x12\n\nyear_stamp\x18\x05 \x01(\t\x12\x0f\n\x07ref_ids\x18\x06 \x03(\t\"9\n\x12UpdateBeatResponse\x12#\n\x04view\x18\x01 \x01(\x0b\x32\x15.rewind.v1.ScriptView\"5\n\x12\x43hooseTitleRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\":\n\x13\x43hooseTitleResponse\x12#\n\x04view\x18\x01 \x01(\x0b\x32\x15.rewind.v1.ScriptView2\xf1\x01\n\x0eScriptsService\x12\x46\n\tGetScript\x12\x1b.rewind.v1.GetScriptRequest\x1a\x1c.rewind.v1.GetScriptResponse\x12I\n\nUpdateBeat\x12\x1c.rewind.v1.UpdateBeatRequest\x1a\x1d.rewind.v1.UpdateBeatResponse\x12L\n\x0b\x43hooseTitle\x12\x1d.rewind.v1.ChooseTitleRequest\x1a\x1e.rewind.v1.ChooseTitleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rewind.v1.scripts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIPTVIEW']._serialized_start=62
  _globals['_SCRIPTVIEW']._serialized_end=172
  _globals['_GETSCRIPTREQUEST']._serialized_start=174
  _globals['_GETSCRIPTREQUEST']._serialized_end=210
  _globals['_GETSCRIPTRESPONSE']._serialized_start=212
  _globals['_GETSCRIPTRESPONSE']._serialized_end=268
  _globals['_UPDATEBEATREQUEST']._serialized_start=270
  _globals['_UPDATEBEATREQUEST']._serialized_end=394
  _globals['_UPDATEBEATRESPONSE']._serialized_start=396
  _globals['_UPDATEBEATRESPONSE']._serialized_end=453
  _globals['_CHOOSETITLEREQUEST']._serialized_start=455
  _globals['_CHOOSETITLEREQUEST']._serialized_end=508
  _globals['_CHOOSETITLERESPONSE']._serialized_start=510
  _globals['_CHOOSETITLERESPONSE']._serialized_end=568
  _globals['_SCRIPTSSERVICE']._serialized_start=571
  _globals['_SCRIPTSSERVICE']._serialized_end=812
# @@protoc_insertion_point(module_scope)
