"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from rewind.v1 import script_pb2 as _script_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ScriptView(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXISTS_FIELD_NUMBER: _builtins.int
    SCRIPT_FIELD_NUMBER: _builtins.int
    CAN_APPROVE_FIELD_NUMBER: _builtins.int
    APPROVAL_BLOCKER_FIELD_NUMBER: _builtins.int
    exists: _builtins.bool
    """False until the script step has run."""
    can_approve: _builtins.bool
    approval_blocker: _builtins.str
    """e.g. "2 rules broken" or "choose a title"."""
    @_builtins.property
    def script(self) -> _script_pb2.Script: ...
    def __init__(
        self,
        *,
        exists: _builtins.bool = ...,
        script: _script_pb2.Script | None = ...,
        can_approve: _builtins.bool = ...,
        approval_blocker: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["script", b"script"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["approval_blocker", b"approval_blocker", "can_approve", b"can_approve", "exists", b"exists", "script", b"script"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScriptView: _TypeAlias = ScriptView  # noqa: Y015

@_typing.final
class GetScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetScriptRequest: _TypeAlias = GetScriptRequest  # noqa: Y015

@_typing.final
class GetScriptResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ScriptView: ...
    def __init__(
        self,
        *,
        view: Global___ScriptView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetScriptResponse: _TypeAlias = GetScriptResponse  # noqa: Y015

@_typing.final
class UpdateBeatRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    N_FIELD_NUMBER: _builtins.int
    VOICE_FIELD_NUMBER: _builtins.int
    ON_SCREEN_TEXT_FIELD_NUMBER: _builtins.int
    YEAR_STAMP_FIELD_NUMBER: _builtins.int
    REF_IDS_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    n: _builtins.int
    """1-based."""
    voice: _builtins.str
    on_screen_text: _builtins.str
    year_stamp: _builtins.str
    @_builtins.property
    def ref_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """The beat's COMPLETE list of comparisons after the edit -- always sent in
        full, since an empty list means "none". Lets the reviewer take a
        comparison out of a beat that does not cite its fact, which a first live
        run showed cannot otherwise be fixed at Gate C. What they choose is
        re-checked like any edit: only comparisons selected at Gate B pass.
        """

    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        n: _builtins.int = ...,
        voice: _builtins.str = ...,
        on_screen_text: _builtins.str = ...,
        year_stamp: _builtins.str = ...,
        ref_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["n", b"n", "on_screen_text", b"on_screen_text", "ref_ids", b"ref_ids", "video_id", b"video_id", "voice", b"voice", "year_stamp", b"year_stamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateBeatRequest: _TypeAlias = UpdateBeatRequest  # noqa: Y015

@_typing.final
class UpdateBeatResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ScriptView: ...
    def __init__(
        self,
        *,
        view: Global___ScriptView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpdateBeatResponse: _TypeAlias = UpdateBeatResponse  # noqa: Y015

@_typing.final
class ChooseTitleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    title: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        title: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["title", b"title", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChooseTitleRequest: _TypeAlias = ChooseTitleRequest  # noqa: Y015

@_typing.final
class ChooseTitleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIEW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def view(self) -> Global___ScriptView: ...
    def __init__(
        self,
        *,
        view: Global___ScriptView | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ChooseTitleResponse: _TypeAlias = ChooseTitleResponse  # noqa: Y015
