# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import scripts_pb2 as rewind_dot_v1_dot_scripts__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/scripts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScriptsServiceStub:
    """ScriptsService is the Gate C surface for the dashboard (SPEC.md 5.4, 8.2).

    Like the other gate services, every mutation returns the whole recomputed
    view. An edit is saved, then re-validated by the worker's rules before the
    view comes back, so the dashboard always shows what is wrong NOW.

    Regenerating the whole script is not here: that is "send back" on the gate
    (VideoService.RejectGate), which reruns the script step and logs why.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScript = channel.unary_unary(
                '/rewind.v1.ScriptsService/GetScript',
                request_serializer=rewind_dot_v1_dot_scripts__pb2.GetScriptRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_scripts__pb2.GetScriptResponse.FromString,
                _registered_method=True)
        self.UpdateBeat = channel.unary_unary(
                '/rewind.v1.ScriptsService/UpdateBeat',
                request_serializer=rewind_dot_v1_dot_scripts__pb2.UpdateBeatRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_scripts__pb2.UpdateBeatResponse.FromString,
                _registered_method=True)
        self.ChooseTitle = channel.unary_unary(
                '/rewind.v1.ScriptsService/ChooseTitle',
                request_serializer=rewind_dot_v1_dot_scripts__pb2.ChooseTitleRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_scripts__pb2.ChooseTitleResponse.FromString,
                _registered_method=True)


class ScriptsServiceServicer:
    """ScriptsService is the Gate C surface for the dashboard (SPEC.md 5.4, 8.2).

    Like the other gate services, every mutation returns the whole recomputed
    view. An edit is saved, then re-validated by the worker's rules before the
    view comes back, so the dashboard always shows what is wrong NOW.

    Regenerating the whole script is not here: that is "send back" on the gate
    (VideoService.RejectGate), which reruns the script step and logs why.
    """

    def GetScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBeat(self, request, context):
        """UpdateBeat rewrites what one beat says or shows.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChooseTitle(self, request, context):
        """ChooseTitle picks one of the title options, or a title typed in full.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScriptsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScript,
                    request_deserializer=rewind_dot_v1_dot_scripts__pb2.GetScriptRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_scripts__pb2.GetScriptResponse.SerializeToString,
            ),
            'UpdateBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBeat,
                    request_deserializer=rewind_dot_v1_dot_scripts__pb2.UpdateBeatRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_scripts__pb2.UpdateBeatResponse.SerializeToString,
            ),
            'ChooseTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.ChooseTitle,
                    request_deserializer=rewind_dot_v1_dot_scripts__pb2.ChooseTitleRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_scripts__pb2.ChooseTitleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.ScriptsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.ScriptsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScriptsService:
    """ScriptsService is the Gate C surface for the dashboard (SPEC.md 5.4, 8.2).

    Like the other gate services, every mutation returns the whole recomputed
    view. An edit is saved, then re-validated by the worker's rules before the
    view comes back, so the dashboard always shows what is wrong NOW.

    Regenerating the whole script is not here: that is "send back" on the gate
    (VideoService.RejectGate), which reruns the script step and logs why.
    """

    @staticmethod
    def GetScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ScriptsService/GetScript',
            rewind_dot_v1_dot_scripts__pb2.GetScriptRequest.SerializeToString,
            rewind_dot_v1_dot_scripts__pb2.GetScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ScriptsService/UpdateBeat',
            rewind_dot_v1_dot_scripts__pb2.UpdateBeatRequest.SerializeToString,
            rewind_dot_v1_dot_scripts__pb2.UpdateBeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChooseTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ScriptsService/ChooseTitle',
            rewind_dot_v1_dot_scripts__pb2.ChooseTitleRequest.SerializeToString,
            rewind_dot_v1_dot_scripts__pb2.ChooseTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
