"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import script_pb2 as _script_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ScriptServiceStub:
    """ScriptService turns approved facts and approved comparisons into a beat
    script, and checks scripts against the rules (SPEC.md 5.4).

    THE RULE THIS SERVICE MUST NOT BREAK: every number in a beat -- spoken, on
    screen, or in its year stamp -- comes from an approved fact that beat cites
    in fact_ids. The script is written by a model; the facts were checked by a
    human. Nothing the model writes may add a number the human did not see.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ScriptServiceAsyncStub: ...
    GenerateScript: _grpc.UnaryStreamMultiCallable[_script_pb2.GenerateScriptRequest, _script_pb2.GenerateScriptResponse]
    """GenerateScript writes script.json: generate, validate, and regenerate
    with the violations fed back, up to the configured attempts.
    """
    ValidateScript: _grpc.UnaryUnaryMultiCallable[_script_pb2.ValidateScriptRequest, _script_pb2.ValidateScriptResponse]
    """ValidateScript checks a script and returns every violation. Stateless and
    model-free, so Go can call it after each inline edit at Gate C: there is
    exactly one implementation of the rules, and it lives here.
    """

@_typing.type_check_only
class ScriptServiceAsyncStub(ScriptServiceStub):
    """ScriptService turns approved facts and approved comparisons into a beat
    script, and checks scripts against the rules (SPEC.md 5.4).

    THE RULE THIS SERVICE MUST NOT BREAK: every number in a beat -- spoken, on
    screen, or in its year stamp -- comes from an approved fact that beat cites
    in fact_ids. The script is written by a model; the facts were checked by a
    human. Nothing the model writes may add a number the human did not see.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    GenerateScript: _aio.UnaryStreamMultiCallable[_script_pb2.GenerateScriptRequest, _script_pb2.GenerateScriptResponse]  # type: ignore[assignment]
    """GenerateScript writes script.json: generate, validate, and regenerate
    with the violations fed back, up to the configured attempts.
    """
    ValidateScript: _aio.UnaryUnaryMultiCallable[_script_pb2.ValidateScriptRequest, _script_pb2.ValidateScriptResponse]  # type: ignore[assignment]
    """ValidateScript checks a script and returns every violation. Stateless and
    model-free, so Go can call it after each inline edit at Gate C: there is
    exactly one implementation of the rules, and it lives here.
    """

class ScriptServiceServicer(metaclass=_abc_1.ABCMeta):
    """ScriptService turns approved facts and approved comparisons into a beat
    script, and checks scripts against the rules (SPEC.md 5.4).

    THE RULE THIS SERVICE MUST NOT BREAK: every number in a beat -- spoken, on
    screen, or in its year stamp -- comes from an approved fact that beat cites
    in fact_ids. The script is written by a model; the facts were checked by a
    human. Nothing the model writes may add a number the human did not see.
    """

    @_abc_1.abstractmethod
    def GenerateScript(
        self,
        request: _script_pb2.GenerateScriptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_script_pb2.GenerateScriptResponse], _abc.AsyncIterator[_script_pb2.GenerateScriptResponse]]:
        """GenerateScript writes script.json: generate, validate, and regenerate
        with the violations fed back, up to the configured attempts.
        """

    @_abc_1.abstractmethod
    def ValidateScript(
        self,
        request: _script_pb2.ValidateScriptRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_script_pb2.ValidateScriptResponse, _abc.Awaitable[_script_pb2.ValidateScriptResponse]]:
        """ValidateScript checks a script and returns every violation. Stateless and
        model-free, so Go can call it after each inline edit at Gate C: there is
        exactly one implementation of the rules, and it lives here.
        """

def add_ScriptServiceServicer_to_server(servicer: ScriptServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
