# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import script_pb2 as rewind_dot_v1_dot_script__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/script_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScriptServiceStub:
    """ScriptService turns approved facts and approved comparisons into a beat
    script, and checks scripts against the rules (SPEC.md 5.4).

    THE RULE THIS SERVICE MUST NOT BREAK: every number in a beat -- spoken, on
    screen, or in its year stamp -- comes from an approved fact that beat cites
    in fact_ids. The script is written by a model; the facts were checked by a
    human. Nothing the model writes may add a number the human did not see.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateScript = channel.unary_stream(
                '/rewind.v1.ScriptService/GenerateScript',
                request_serializer=rewind_dot_v1_dot_script__pb2.GenerateScriptRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_script__pb2.GenerateScriptResponse.FromString,
                _registered_method=True)
        self.ValidateScript = channel.unary_unary(
                '/rewind.v1.ScriptService/ValidateScript',
                request_serializer=rewind_dot_v1_dot_script__pb2.ValidateScriptRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_script__pb2.ValidateScriptResponse.FromString,
                _registered_method=True)


class ScriptServiceServicer:
    """ScriptService turns approved facts and approved comparisons into a beat
    script, and checks scripts against the rules (SPEC.md 5.4).

    THE RULE THIS SERVICE MUST NOT BREAK: every number in a beat -- spoken, on
    screen, or in its year stamp -- comes from an approved fact that beat cites
    in fact_ids. The script is written by a model; the facts were checked by a
    human. Nothing the model writes may add a number the human did not see.
    """

    def GenerateScript(self, request, context):
        """GenerateScript writes script.json: generate, validate, and regenerate
        with the violations fed back, up to the configured attempts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateScript(self, request, context):
        """ValidateScript checks a script and returns every violation. Stateless and
        model-free, so Go can call it after each inline edit at Gate C: there is
        exactly one implementation of the rules, and it lives here.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScriptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateScript': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateScript,
                    request_deserializer=rewind_dot_v1_dot_script__pb2.GenerateScriptRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_script__pb2.GenerateScriptResponse.SerializeToString,
            ),
            'ValidateScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateScript,
                    request_deserializer=rewind_dot_v1_dot_script__pb2.ValidateScriptRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_script__pb2.ValidateScriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.ScriptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.ScriptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScriptService:
    """ScriptService turns approved facts and approved comparisons into a beat
    script, and checks scripts against the rules (SPEC.md 5.4).

    THE RULE THIS SERVICE MUST NOT BREAK: every number in a beat -- spoken, on
    screen, or in its year stamp -- comes from an approved fact that beat cites
    in fact_ids. The script is written by a model; the facts were checked by a
    human. Nothing the model writes may add a number the human did not see.
    """

    @staticmethod
    def GenerateScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rewind.v1.ScriptService/GenerateScript',
            rewind_dot_v1_dot_script__pb2.GenerateScriptRequest.SerializeToString,
            rewind_dot_v1_dot_script__pb2.GenerateScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.ScriptService/ValidateScript',
            rewind_dot_v1_dot_script__pb2.ValidateScriptRequest.SerializeToString,
            rewind_dot_v1_dot_script__pb2.ValidateScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
