# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rewind.v1 import video_pb2 as rewind_dot_v1_dot_video__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rewind/v1/video_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoServiceStub:
    """VideoService is the dashboard's view of the pipeline: the queue, each
    video's state, and the six human review gates.

    Served by Go over Connect (JSON over HTTP) because browsers cannot speak
    native gRPC. The same operations are available from the `rewind` CLI, and
    both go through the identical service layer -- there is no second code path
    that could enforce different rules.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddVideo = channel.unary_unary(
                '/rewind.v1.VideoService/AddVideo',
                request_serializer=rewind_dot_v1_dot_video__pb2.AddVideoRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.AddVideoResponse.FromString,
                _registered_method=True)
        self.ListVideos = channel.unary_unary(
                '/rewind.v1.VideoService/ListVideos',
                request_serializer=rewind_dot_v1_dot_video__pb2.ListVideosRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.ListVideosResponse.FromString,
                _registered_method=True)
        self.GetVideo = channel.unary_unary(
                '/rewind.v1.VideoService/GetVideo',
                request_serializer=rewind_dot_v1_dot_video__pb2.GetVideoRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.GetVideoResponse.FromString,
                _registered_method=True)
        self.ApproveGate = channel.unary_unary(
                '/rewind.v1.VideoService/ApproveGate',
                request_serializer=rewind_dot_v1_dot_video__pb2.ApproveGateRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.ApproveGateResponse.FromString,
                _registered_method=True)
        self.RejectGate = channel.unary_unary(
                '/rewind.v1.VideoService/RejectGate',
                request_serializer=rewind_dot_v1_dot_video__pb2.RejectGateRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.RejectGateResponse.FromString,
                _registered_method=True)
        self.RetryVideo = channel.unary_unary(
                '/rewind.v1.VideoService/RetryVideo',
                request_serializer=rewind_dot_v1_dot_video__pb2.RetryVideoRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.RetryVideoResponse.FromString,
                _registered_method=True)
        self.ListReviewLog = channel.unary_unary(
                '/rewind.v1.VideoService/ListReviewLog',
                request_serializer=rewind_dot_v1_dot_video__pb2.ListReviewLogRequest.SerializeToString,
                response_deserializer=rewind_dot_v1_dot_video__pb2.ListReviewLogResponse.FromString,
                _registered_method=True)


class VideoServiceServicer:
    """VideoService is the dashboard's view of the pipeline: the queue, each
    video's state, and the six human review gates.

    Served by Go over Connect (JSON over HTTP) because browsers cannot speak
    native gRPC. The same operations are available from the `rewind` CLI, and
    both go through the identical service layer -- there is no second code path
    that could enforce different rules.
    """

    def AddVideo(self, request, context):
        """AddVideo queues a new topic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVideos(self, request, context):
        """ListVideos returns the queue, newest-relevant first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideo(self, request, context):
        """GetVideo returns one video.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveGate(self, request, context):
        """ApproveGate records a human approval and advances the video.

        This is the ONLY way a video crosses a gate. Ordinary pipeline
        transitions physically cannot produce a gate-crossing state change, so a
        gate cannot be skipped even by a buggy step (SPEC.md 2.2).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectGate(self, request, context):
        """RejectGate sends a video back to an earlier state with a note.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryVideo(self, request, context):
        """RetryVideo resumes a video that failed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReviewLog(self, request, context):
        """ListReviewLog returns the human-decision history for one video. This log
        is the project's proof of human creative involvement (SPEC.md 8.4).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVideo,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.AddVideoRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.AddVideoResponse.SerializeToString,
            ),
            'ListVideos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVideos,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.ListVideosRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.ListVideosResponse.SerializeToString,
            ),
            'GetVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideo,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.GetVideoRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.GetVideoResponse.SerializeToString,
            ),
            'ApproveGate': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveGate,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.ApproveGateRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.ApproveGateResponse.SerializeToString,
            ),
            'RejectGate': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectGate,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.RejectGateRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.RejectGateResponse.SerializeToString,
            ),
            'RetryVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryVideo,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.RetryVideoRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.RetryVideoResponse.SerializeToString,
            ),
            'ListReviewLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReviewLog,
                    request_deserializer=rewind_dot_v1_dot_video__pb2.ListReviewLogRequest.FromString,
                    response_serializer=rewind_dot_v1_dot_video__pb2.ListReviewLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rewind.v1.VideoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rewind.v1.VideoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoService:
    """VideoService is the dashboard's view of the pipeline: the queue, each
    video's state, and the six human review gates.

    Served by Go over Connect (JSON over HTTP) because browsers cannot speak
    native gRPC. The same operations are available from the `rewind` CLI, and
    both go through the identical service layer -- there is no second code path
    that could enforce different rules.
    """

    @staticmethod
    def AddVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/AddVideo',
            rewind_dot_v1_dot_video__pb2.AddVideoRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.AddVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVideos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/ListVideos',
            rewind_dot_v1_dot_video__pb2.ListVideosRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.ListVideosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/GetVideo',
            rewind_dot_v1_dot_video__pb2.GetVideoRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.GetVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/ApproveGate',
            rewind_dot_v1_dot_video__pb2.ApproveGateRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.ApproveGateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/RejectGate',
            rewind_dot_v1_dot_video__pb2.RejectGateRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.RejectGateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/RetryVideo',
            rewind_dot_v1_dot_video__pb2.RetryVideoRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.RetryVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReviewLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rewind.v1.VideoService/ListReviewLog',
            rewind_dot_v1_dot_video__pb2.ListReviewLogRequest.SerializeToString,
            rewind_dot_v1_dot_video__pb2.ListReviewLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
