"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from rewind.v1 import video_pb2 as _video_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class VideoServiceStub:
    """VideoService is the dashboard's view of the pipeline: the queue, each
    video's state, and the six human review gates.

    Served by Go over Connect (JSON over HTTP) because browsers cannot speak
    native gRPC. The same operations are available from the `rewind` CLI, and
    both go through the identical service layer -- there is no second code path
    that could enforce different rules.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> VideoServiceAsyncStub: ...
    AddVideo: _grpc.UnaryUnaryMultiCallable[_video_pb2.AddVideoRequest, _video_pb2.AddVideoResponse]
    """AddVideo queues a new topic."""
    ListVideos: _grpc.UnaryUnaryMultiCallable[_video_pb2.ListVideosRequest, _video_pb2.ListVideosResponse]
    """ListVideos returns the queue, newest-relevant first."""
    GetVideo: _grpc.UnaryUnaryMultiCallable[_video_pb2.GetVideoRequest, _video_pb2.GetVideoResponse]
    """GetVideo returns one video."""
    ApproveGate: _grpc.UnaryUnaryMultiCallable[_video_pb2.ApproveGateRequest, _video_pb2.ApproveGateResponse]
    """ApproveGate records a human approval and advances the video.

    This is the ONLY way a video crosses a gate. Ordinary pipeline
    transitions physically cannot produce a gate-crossing state change, so a
    gate cannot be skipped even by a buggy step (SPEC.md 2.2).
    """
    RejectGate: _grpc.UnaryUnaryMultiCallable[_video_pb2.RejectGateRequest, _video_pb2.RejectGateResponse]
    """RejectGate sends a video back to an earlier state with a note."""
    RetryVideo: _grpc.UnaryUnaryMultiCallable[_video_pb2.RetryVideoRequest, _video_pb2.RetryVideoResponse]
    """RetryVideo resumes a video that failed."""
    ListReviewLog: _grpc.UnaryUnaryMultiCallable[_video_pb2.ListReviewLogRequest, _video_pb2.ListReviewLogResponse]
    """ListReviewLog returns the human-decision history for one video. This log
    is the project's proof of human creative involvement (SPEC.md 8.4).
    """

@_typing.type_check_only
class VideoServiceAsyncStub(VideoServiceStub):
    """VideoService is the dashboard's view of the pipeline: the queue, each
    video's state, and the six human review gates.

    Served by Go over Connect (JSON over HTTP) because browsers cannot speak
    native gRPC. The same operations are available from the `rewind` CLI, and
    both go through the identical service layer -- there is no second code path
    that could enforce different rules.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    AddVideo: _aio.UnaryUnaryMultiCallable[_video_pb2.AddVideoRequest, _video_pb2.AddVideoResponse]  # type: ignore[assignment]
    """AddVideo queues a new topic."""
    ListVideos: _aio.UnaryUnaryMultiCallable[_video_pb2.ListVideosRequest, _video_pb2.ListVideosResponse]  # type: ignore[assignment]
    """ListVideos returns the queue, newest-relevant first."""
    GetVideo: _aio.UnaryUnaryMultiCallable[_video_pb2.GetVideoRequest, _video_pb2.GetVideoResponse]  # type: ignore[assignment]
    """GetVideo returns one video."""
    ApproveGate: _aio.UnaryUnaryMultiCallable[_video_pb2.ApproveGateRequest, _video_pb2.ApproveGateResponse]  # type: ignore[assignment]
    """ApproveGate records a human approval and advances the video.

    This is the ONLY way a video crosses a gate. Ordinary pipeline
    transitions physically cannot produce a gate-crossing state change, so a
    gate cannot be skipped even by a buggy step (SPEC.md 2.2).
    """
    RejectGate: _aio.UnaryUnaryMultiCallable[_video_pb2.RejectGateRequest, _video_pb2.RejectGateResponse]  # type: ignore[assignment]
    """RejectGate sends a video back to an earlier state with a note."""
    RetryVideo: _aio.UnaryUnaryMultiCallable[_video_pb2.RetryVideoRequest, _video_pb2.RetryVideoResponse]  # type: ignore[assignment]
    """RetryVideo resumes a video that failed."""
    ListReviewLog: _aio.UnaryUnaryMultiCallable[_video_pb2.ListReviewLogRequest, _video_pb2.ListReviewLogResponse]  # type: ignore[assignment]
    """ListReviewLog returns the human-decision history for one video. This log
    is the project's proof of human creative involvement (SPEC.md 8.4).
    """

class VideoServiceServicer(metaclass=_abc_1.ABCMeta):
    """VideoService is the dashboard's view of the pipeline: the queue, each
    video's state, and the six human review gates.

    Served by Go over Connect (JSON over HTTP) because browsers cannot speak
    native gRPC. The same operations are available from the `rewind` CLI, and
    both go through the identical service layer -- there is no second code path
    that could enforce different rules.
    """

    @_abc_1.abstractmethod
    def AddVideo(
        self,
        request: _video_pb2.AddVideoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.AddVideoResponse, _abc.Awaitable[_video_pb2.AddVideoResponse]]:
        """AddVideo queues a new topic."""

    @_abc_1.abstractmethod
    def ListVideos(
        self,
        request: _video_pb2.ListVideosRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.ListVideosResponse, _abc.Awaitable[_video_pb2.ListVideosResponse]]:
        """ListVideos returns the queue, newest-relevant first."""

    @_abc_1.abstractmethod
    def GetVideo(
        self,
        request: _video_pb2.GetVideoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.GetVideoResponse, _abc.Awaitable[_video_pb2.GetVideoResponse]]:
        """GetVideo returns one video."""

    @_abc_1.abstractmethod
    def ApproveGate(
        self,
        request: _video_pb2.ApproveGateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.ApproveGateResponse, _abc.Awaitable[_video_pb2.ApproveGateResponse]]:
        """ApproveGate records a human approval and advances the video.

        This is the ONLY way a video crosses a gate. Ordinary pipeline
        transitions physically cannot produce a gate-crossing state change, so a
        gate cannot be skipped even by a buggy step (SPEC.md 2.2).
        """

    @_abc_1.abstractmethod
    def RejectGate(
        self,
        request: _video_pb2.RejectGateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.RejectGateResponse, _abc.Awaitable[_video_pb2.RejectGateResponse]]:
        """RejectGate sends a video back to an earlier state with a note."""

    @_abc_1.abstractmethod
    def RetryVideo(
        self,
        request: _video_pb2.RetryVideoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.RetryVideoResponse, _abc.Awaitable[_video_pb2.RetryVideoResponse]]:
        """RetryVideo resumes a video that failed."""

    @_abc_1.abstractmethod
    def ListReviewLog(
        self,
        request: _video_pb2.ListReviewLogRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.ListReviewLogResponse, _abc.Awaitable[_video_pb2.ListReviewLogResponse]]:
        """ListReviewLog returns the human-decision history for one video. This log
        is the project's proof of human creative involvement (SPEC.md 8.4).
        """

def add_VideoServiceServicer_to_server(servicer: VideoServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
