"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _VideoStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VideoStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VideoStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VIDEO_STATUS_UNSPECIFIED: _VideoStatus.ValueType  # 0
    VIDEO_STATUS_QUEUED: _VideoStatus.ValueType  # 1
    VIDEO_STATUS_RESEARCHING: _VideoStatus.ValueType  # 2
    """Module 2 -- research, then Gate A"""
    VIDEO_STATUS_FACTS_READY: _VideoStatus.ValueType  # 3
    VIDEO_STATUS_FACTS_APPROVED: _VideoStatus.ValueType  # 4
    VIDEO_STATUS_FINDING_REFS: _VideoStatus.ValueType  # 5
    """Module 3 -- relevance, then Gate B"""
    VIDEO_STATUS_REFS_READY: _VideoStatus.ValueType  # 6
    VIDEO_STATUS_REFS_APPROVED: _VideoStatus.ValueType  # 7
    VIDEO_STATUS_SCRIPTING: _VideoStatus.ValueType  # 8
    """Module 4 -- script, then Gate C"""
    VIDEO_STATUS_SCRIPT_READY: _VideoStatus.ValueType  # 9
    VIDEO_STATUS_SCRIPT_APPROVED: _VideoStatus.ValueType  # 10
    VIDEO_STATUS_VOICING: _VideoStatus.ValueType  # 11
    """Module 5 -- voice, then Gate D"""
    VIDEO_STATUS_VOICE_READY: _VideoStatus.ValueType  # 12
    VIDEO_STATUS_VOICE_APPROVED: _VideoStatus.ValueType  # 13
    VIDEO_STATUS_IMAGING: _VideoStatus.ValueType  # 14
    """Module 6 -- visuals, then Gate E"""
    VIDEO_STATUS_STORYBOARD_READY: _VideoStatus.ValueType  # 15
    VIDEO_STATUS_STORYBOARD_APPROVED: _VideoStatus.ValueType  # 16
    VIDEO_STATUS_RENDERING: _VideoStatus.ValueType  # 17
    """Module 9 -- render, then Gate F"""
    VIDEO_STATUS_RENDER_READY: _VideoStatus.ValueType  # 18
    VIDEO_STATUS_FINAL_APPROVED: _VideoStatus.ValueType  # 19
    VIDEO_STATUS_UPLOADING: _VideoStatus.ValueType  # 20
    """Module 10 -- publish. Always private; a human publishes manually."""
    VIDEO_STATUS_UPLOADED_PRIVATE: _VideoStatus.ValueType  # 21
    VIDEO_STATUS_PUBLISHED: _VideoStatus.ValueType  # 22
    VIDEO_STATUS_ANALYTICS_COLLECTED: _VideoStatus.ValueType  # 23
    """Module 11 -- analytics"""
    VIDEO_STATUS_ERROR: _VideoStatus.ValueType  # 24
    """A step failed. `error` carries the message; RetryVideo resumes."""

class VideoStatus(_VideoStatus, metaclass=_VideoStatusEnumTypeWrapper):
    """VideoStatus mirrors the state machine in SPEC.md 2.3.

    Names are explicit rather than clever: the wire value is what appears in the
    database, the CLI and the dashboard, so it has to read well everywhere.
    """

VIDEO_STATUS_UNSPECIFIED: VideoStatus.ValueType  # 0
VIDEO_STATUS_QUEUED: VideoStatus.ValueType  # 1
VIDEO_STATUS_RESEARCHING: VideoStatus.ValueType  # 2
"""Module 2 -- research, then Gate A"""
VIDEO_STATUS_FACTS_READY: VideoStatus.ValueType  # 3
VIDEO_STATUS_FACTS_APPROVED: VideoStatus.ValueType  # 4
VIDEO_STATUS_FINDING_REFS: VideoStatus.ValueType  # 5
"""Module 3 -- relevance, then Gate B"""
VIDEO_STATUS_REFS_READY: VideoStatus.ValueType  # 6
VIDEO_STATUS_REFS_APPROVED: VideoStatus.ValueType  # 7
VIDEO_STATUS_SCRIPTING: VideoStatus.ValueType  # 8
"""Module 4 -- script, then Gate C"""
VIDEO_STATUS_SCRIPT_READY: VideoStatus.ValueType  # 9
VIDEO_STATUS_SCRIPT_APPROVED: VideoStatus.ValueType  # 10
VIDEO_STATUS_VOICING: VideoStatus.ValueType  # 11
"""Module 5 -- voice, then Gate D"""
VIDEO_STATUS_VOICE_READY: VideoStatus.ValueType  # 12
VIDEO_STATUS_VOICE_APPROVED: VideoStatus.ValueType  # 13
VIDEO_STATUS_IMAGING: VideoStatus.ValueType  # 14
"""Module 6 -- visuals, then Gate E"""
VIDEO_STATUS_STORYBOARD_READY: VideoStatus.ValueType  # 15
VIDEO_STATUS_STORYBOARD_APPROVED: VideoStatus.ValueType  # 16
VIDEO_STATUS_RENDERING: VideoStatus.ValueType  # 17
"""Module 9 -- render, then Gate F"""
VIDEO_STATUS_RENDER_READY: VideoStatus.ValueType  # 18
VIDEO_STATUS_FINAL_APPROVED: VideoStatus.ValueType  # 19
VIDEO_STATUS_UPLOADING: VideoStatus.ValueType  # 20
"""Module 10 -- publish. Always private; a human publishes manually."""
VIDEO_STATUS_UPLOADED_PRIVATE: VideoStatus.ValueType  # 21
VIDEO_STATUS_PUBLISHED: VideoStatus.ValueType  # 22
VIDEO_STATUS_ANALYTICS_COLLECTED: VideoStatus.ValueType  # 23
"""Module 11 -- analytics"""
VIDEO_STATUS_ERROR: VideoStatus.ValueType  # 24
"""A step failed. `error` carries the message; RetryVideo resumes."""
Global___VideoStatus: _TypeAlias = VideoStatus  # noqa: Y015

class _Gate:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Gate.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GATE_UNSPECIFIED: _Gate.ValueType  # 0
    GATE_A_FACTS: _Gate.ValueType  # 1
    GATE_B_REFERENCES: _Gate.ValueType  # 2
    GATE_C_SCRIPT: _Gate.ValueType  # 3
    GATE_D_VOICE: _Gate.ValueType  # 4
    GATE_E_STORYBOARD: _Gate.ValueType  # 5
    GATE_F_FINAL: _Gate.ValueType  # 6

class Gate(_Gate, metaclass=_GateEnumTypeWrapper):
    """Gate identifies one of the six human review points (SPEC.md 2.2)."""

GATE_UNSPECIFIED: Gate.ValueType  # 0
GATE_A_FACTS: Gate.ValueType  # 1
GATE_B_REFERENCES: Gate.ValueType  # 2
GATE_C_SCRIPT: Gate.ValueType  # 3
GATE_D_VOICE: Gate.ValueType  # 4
GATE_E_STORYBOARD: Gate.ValueType  # 5
GATE_F_FINAL: Gate.ValueType  # 6
Global___Gate: _TypeAlias = Gate  # noqa: Y015

@_typing.final
class Video(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    NOTES_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    REJECTED_TO_FIELD_NUMBER: _builtins.int
    REJECT_NOTE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    RETRY_FROM_FIELD_NUMBER: _builtins.int
    YT_VIDEO_ID_FIELD_NUMBER: _builtins.int
    PUBLISHED_AT_FIELD_NUMBER: _builtins.int
    AWAITING_GATE_FIELD_NUMBER: _builtins.int
    IS_TERMINAL_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """slug, e.g. "computer-mouse" """
    topic: _builtins.str
    """as typed, e.g. "computer mouse" """
    status: Global___VideoStatus.ValueType
    priority: _builtins.int
    """1 is highest, 5 lowest, 3 the default."""
    notes: _builtins.str
    created_at: _builtins.str
    """RFC 3339"""
    updated_at: _builtins.str
    """RFC 3339"""
    rejected_to: Global___VideoStatus.ValueType
    """Set when a gate sent this video back; cleared once it moves forward again."""
    reject_note: _builtins.str
    error: _builtins.str
    """Set when status is ERROR."""
    retry_from: Global___VideoStatus.ValueType
    """The status to resume from on retry."""
    yt_video_id: _builtins.str
    published_at: _builtins.str
    awaiting_gate: Global___Gate.ValueType
    """Derived, so every client agrees rather than each recomputing it.
    GATE_UNSPECIFIED when not waiting on a human
    """
    is_terminal: _builtins.bool
    """nothing further will happen on its own"""
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        topic: _builtins.str = ...,
        status: Global___VideoStatus.ValueType = ...,
        priority: _builtins.int = ...,
        notes: _builtins.str = ...,
        created_at: _builtins.str = ...,
        updated_at: _builtins.str = ...,
        rejected_to: Global___VideoStatus.ValueType = ...,
        reject_note: _builtins.str = ...,
        error: _builtins.str = ...,
        retry_from: Global___VideoStatus.ValueType = ...,
        yt_video_id: _builtins.str = ...,
        published_at: _builtins.str = ...,
        awaiting_gate: Global___Gate.ValueType = ...,
        is_terminal: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["awaiting_gate", b"awaiting_gate", "created_at", b"created_at", "error", b"error", "id", b"id", "is_terminal", b"is_terminal", "notes", b"notes", "priority", b"priority", "published_at", b"published_at", "reject_note", b"reject_note", "rejected_to", b"rejected_to", "retry_from", b"retry_from", "status", b"status", "topic", b"topic", "updated_at", b"updated_at", "yt_video_id", b"yt_video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Video: _TypeAlias = Video  # noqa: Y015

@_typing.final
class AddVideoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    PRIORITY_FIELD_NUMBER: _builtins.int
    NOTES_FIELD_NUMBER: _builtins.int
    topic: _builtins.str
    """Free text, e.g. "computer mouse". The id is derived from it."""
    priority: _builtins.int
    """0 means use the default"""
    notes: _builtins.str
    def __init__(
        self,
        *,
        topic: _builtins.str = ...,
        priority: _builtins.int = ...,
        notes: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["notes", b"notes", "priority", b"priority", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddVideoRequest: _TypeAlias = AddVideoRequest  # noqa: Y015

@_typing.final
class AddVideoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video(self) -> Global___Video: ...
    def __init__(
        self,
        *,
        video: Global___Video | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddVideoResponse: _TypeAlias = AddVideoResponse  # noqa: Y015

@_typing.final
class ListVideosRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NEEDS_REVIEW_ONLY_FIELD_NUMBER: _builtins.int
    STATUSES_FIELD_NUMBER: _builtins.int
    needs_review_only: _builtins.bool
    """When true, return only videos waiting on a human decision."""
    @_builtins.property
    def statuses(self) -> _containers.RepeatedScalarFieldContainer[Global___VideoStatus.ValueType]:
        """Optional status filter; empty means all."""

    def __init__(
        self,
        *,
        needs_review_only: _builtins.bool = ...,
        statuses: _abc.Iterable[Global___VideoStatus.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["needs_review_only", b"needs_review_only", "statuses", b"statuses"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVideosRequest: _TypeAlias = ListVideosRequest  # noqa: Y015

@_typing.final
class ListVideosResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEOS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def videos(self) -> _containers.RepeatedCompositeFieldContainer[Global___Video]: ...
    def __init__(
        self,
        *,
        videos: _abc.Iterable[Global___Video] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["videos", b"videos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVideosResponse: _TypeAlias = ListVideosResponse  # noqa: Y015

@_typing.final
class GetVideoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetVideoRequest: _TypeAlias = GetVideoRequest  # noqa: Y015

@_typing.final
class GetVideoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video(self) -> Global___Video: ...
    def __init__(
        self,
        *,
        video: Global___Video | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetVideoResponse: _TypeAlias = GetVideoResponse  # noqa: Y015

@_typing.final
class ApproveGateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    GATE_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    gate: Global___Gate.ValueType
    """The gate being approved. Required, and must match the video's current
    state: naming the wrong gate is rejected rather than guessed at, so a
    stale browser tab cannot approve something the human is not looking at.
    """
    note: _builtins.str
    """Optional note recorded in the review log."""
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        gate: Global___Gate.ValueType = ...,
        note: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gate", b"gate", "note", b"note", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApproveGateRequest: _TypeAlias = ApproveGateRequest  # noqa: Y015

@_typing.final
class ApproveGateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video(self) -> Global___Video: ...
    def __init__(
        self,
        *,
        video: Global___Video | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ApproveGateResponse: _TypeAlias = ApproveGateResponse  # noqa: Y015

@_typing.final
class RejectGateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    GATE_FIELD_NUMBER: _builtins.int
    BACK_TO_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    gate: Global___Gate.ValueType
    back_to: Global___VideoStatus.ValueType
    """Where to send the video back to. Must be an earlier state."""
    note: _builtins.str
    """Why. Required: a rejection with no reason is useless to the person who
    picks the video up later, including you next week.
    """
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
        gate: Global___Gate.ValueType = ...,
        back_to: Global___VideoStatus.ValueType = ...,
        note: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["back_to", b"back_to", "gate", b"gate", "note", b"note", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RejectGateRequest: _TypeAlias = RejectGateRequest  # noqa: Y015

@_typing.final
class RejectGateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video(self) -> Global___Video: ...
    def __init__(
        self,
        *,
        video: Global___Video | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RejectGateResponse: _TypeAlias = RejectGateResponse  # noqa: Y015

@_typing.final
class RetryVideoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RetryVideoRequest: _TypeAlias = RetryVideoRequest  # noqa: Y015

@_typing.final
class RetryVideoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video(self) -> Global___Video: ...
    def __init__(
        self,
        *,
        video: Global___Video | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RetryVideoResponse: _TypeAlias = RetryVideoResponse  # noqa: Y015

@_typing.final
class ListReviewLogRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_ID_FIELD_NUMBER: _builtins.int
    video_id: _builtins.str
    def __init__(
        self,
        *,
        video_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListReviewLogRequest: _TypeAlias = ListReviewLogRequest  # noqa: Y015

@_typing.final
class ListReviewLogResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___ReviewLogEntry]: ...
    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___ReviewLogEntry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListReviewLogResponse: _TypeAlias = ListReviewLogResponse  # noqa: Y015

@_typing.final
class ReviewLogEntry(_message.Message):
    """ReviewLogEntry is one human decision. Append-only."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    VIDEO_ID_FIELD_NUMBER: _builtins.int
    AT_FIELD_NUMBER: _builtins.int
    GATE_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    FROM_STATUS_FIELD_NUMBER: _builtins.int
    TO_STATUS_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    DIFF_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    video_id: _builtins.str
    at: _builtins.str
    """RFC 3339"""
    gate: Global___Gate.ValueType
    action: _builtins.str
    """"approve" | "reject" | "edit" | "retry" """
    from_status: Global___VideoStatus.ValueType
    to_status: Global___VideoStatus.ValueType
    note: _builtins.str
    diff: _builtins.str
    """JSON describing what the human changed, for edits."""
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        video_id: _builtins.str = ...,
        at: _builtins.str = ...,
        gate: Global___Gate.ValueType = ...,
        action: _builtins.str = ...,
        from_status: Global___VideoStatus.ValueType = ...,
        to_status: Global___VideoStatus.ValueType = ...,
        note: _builtins.str = ...,
        diff: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "at", b"at", "diff", b"diff", "from_status", b"from_status", "gate", b"gate", "id", b"id", "note", b"note", "to_status", b"to_status", "video_id", b"video_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReviewLogEntry: _TypeAlias = ReviewLogEntry  # noqa: Y015
